CREATE TABLE AAP_APPROVAL_SETUP 
(
  APPROVAL_ADMIN_ID NUMBER NOT NULL 
, ACQUISITION_USER_GRP VARCHAR2(40 BYTE) 
, BUDGET_USER_GROUP VARCHAR2(40 BYTE) 
, ACQUISITION_POC VARCHAR2(30 BYTE) 
, BUDGET_POC VARCHAR2(30 BYTE) 
, CENTER VARCHAR2(20 BYTE) 
, CONSTRAINT AAP_APPROVAL_SETUP_PK PRIMARY KEY 
  (
    APPROVAL_ADMIN_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_REFERENCE 
(
  REFERENCE_ID NUMBER NOT NULL 
, REFERENCE_CODE VARCHAR2(30 BYTE) NOT NULL 
, REFERENCE_DESCRIPTION VARCHAR2(150 BYTE) NOT NULL 
, REFERENCE_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT APS_REFERENCE_PK PRIMARY KEY 
  (
    REFERENCE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_REQUESTS 
(
  CTR_LN_ITM_NO VARCHAR2(20 BYTE) NOT NULL 
, ACQUISITION_STATUS NUMBER 
, PRIORITY_LEVEL NUMBER 
, RECURRING_ITEM VARCHAR2(5 BYTE) 
, ZERO_DOLLAR_REQN VARCHAR2(5 BYTE) 
, REQUISITION_NO VARCHAR2(20 BYTE) 
, EXISTING_DOC_NO VARCHAR2(20 BYTE) 
, RELEASE_NUMBER VARCHAR2(20 BYTE) 
, REQUIREMENT_TYPE NUMBER 
, OPTION_YR_EXERCISE NUMBER 
, DETAILED_DESCRIPTION VARCHAR2(1024 BYTE) 
, REQUIRED_AWARD_DATE DATE 
, CURR_YR_POP_END_DATE DATE 
, ANTICIPATED_ACTION_TYPE NUMBER 
, POTENTIAL_CONTRACT_TYPE NUMBER 
, COMMODITY_TYPE NUMBER 
, ANTICIPATED_ACQUISITION_METHOD NUMBER 
, PRODUCT_SERVICE_CODE NUMBER 
, NAICS_CODE NUMBER 
, ESTIMATED_TOTAL_PROJ_VALUE VARCHAR2(20 BYTE) 
, TOTAL_DLARS_FOR_CURT_FY NUMBER 
, PROJECT_POP_START_DATE DATE 
, PROJECT_POP_END_DATE DATE 
, ANTICIPATED_POP VARCHAR2(20 BYTE) 
, COLLABORATION_FLAG VARCHAR2(1 BYTE) 
, COLLABORATION_ITEM_NO VARCHAR2(20 BYTE) 
, LEAD_MNG_CENTER NUMBER 
, OWNER_NM_TEL_NO VARCHAR2(20 BYTE) 
, ESTIMATED_RFA_REL_DATE DATE 
, GRANTS_COMMODITY NUMBER 
, NCIBOARD_REVIEW_REQUIRED VARCHAR2(20 BYTE) 
, ANTICIPATED_NO_OF_AWARDS VARCHAR2(20 BYTE) 
, EXISTING_IAA_NUMBER VARCHAR2(20 BYTE) 
, PURPOSE VARCHAR2(40 BYTE) 
, ESTIMATED_NUMBER_OF_ACTIONS VARCHAR2(20 BYTE) 
, SERVICE_OR_REIMBURSABLE NUMBER 
, REIMBURSABLE_AMT VARCHAR2(20 BYTE) 
, REIMBURSABLE_AGENCY VARCHAR2(20 BYTE) 
, SUBMIT_FLAG CHAR(1 BYTE) 
, CENTER_ID VARCHAR2(5 BYTE) 
, REQUEST_ID NUMBER NOT NULL 
, FISCAL_YEAR NUMBER 
, CREATED_BY VARCHAR2(40 BYTE) 
, CREATED_DATE DATE 
, LAST_UPDATED_BY VARCHAR2(40 BYTE) 
, LAST_UPDATED_DATE DATE 
, CONSTRAINT REQUESTS_PK PRIMARY KEY 
  (
    REQUEST_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_SECURITY_GROUPS 
(
  SECURITY_GROUP_ID NUMBER NOT NULL 
, GROUP_NAME VARCHAR2(30 BYTE) NOT NULL 
, FRIENDLY_NAME VARCHAR2(100 BYTE) 
, LAST_UPDATED_BY VARCHAR2(40 BYTE) 
, LAST_UPDATED_DATE DATE 
, CONSTRAINT AAP_SECURITY_GROUPS_PK PRIMARY KEY 
  (
    SECURITY_GROUP_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_ADMIN 
(
  AAP_ADMIN_ID NUMBER NOT NULL 
, PARAMETER_DESCRIPTION VARCHAR2(20 BYTE) NOT NULL 
, PARAMETER_VALUE VARCHAR2(20 BYTE) 
, CREATED_BY VARCHAR2(50 BYTE) 
, CREATED_DATE DATE 
, LAST_UPDATED_BY VARCHAR2(50 BYTE) 
, LAST_UPDATED_DATE DATE 
, PARAMETER_NAME VARCHAR2(50 BYTE) 
, CONSTRAINT AAP_ADMIN_PK PRIMARY KEY 
  (
    AAP_ADMIN_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_NOTIFICATION 
(
  NOTIFICATION_ID NUMBER NOT NULL 
, REQUEST_ID NUMBER NOT NULL 
, SUBMITTED_FROM VARCHAR2(20 BYTE) NOT NULL 
, SUBMITTED_TO VARCHAR2(20 BYTE) NOT NULL 
, WF_STATUS VARCHAR2(20 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_DATE DATE 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, LAST_UPDATED_DATE DATE 
, CENTER_ITEM_NO VARCHAR2(40 BYTE) 
, CONSTRAINT AAP_NOTIFICATION_PK PRIMARY KEY 
  (
    NOTIFICATION_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_POINT_OF_CONTACT 
(
  POC_ID NUMBER NOT NULL 
, POC_FIRST_NAME VARCHAR2(100 BYTE) NOT NULL 
, POC_LAST_NAME VARCHAR2(100 BYTE) NOT NULL 
, POC_EMAIL VARCHAR2(100 BYTE) NOT NULL 
, POC_TEL VARCHAR2(20 BYTE) 
, CREATED_DATE DATE 
, CREATED_BY VARCHAR2(50 BYTE) 
, LAST_UPDATED_DATE DATE 
, LAST_UPDATED_BY VARCHAR2(20 BYTE) 
, REQUEST_ID NUMBER 
, CONSTRAINT POINT_OF_CONTACT_PK PRIMARY KEY 
  (
    POC_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_DETAILED_EXPENSES 
(
  EXPENSES_ID NUMBER NOT NULL 
, CENTER_ITM_NO VARCHAR2(20 BYTE) 
, FUNDING_OBJ_CODE VARCHAR2(30 BYTE) 
, FUND VARCHAR2(20 BYTE) 
, ALLOWANCE VARCHAR2(20 BYTE) 
, SUB_ALLOWANCE VARCHAR2(20 BYTE) 
, COST_CENTER VARCHAR2(20 BYTE) 
, COST NUMBER 
, REQUEST_ID NUMBER 
, CONSTRAINT DETAILED_EXPENSES_PK PRIMARY KEY 
  (
    EXPENSES_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_ACTION_TYPE_MAINTENANCE 
(
  ID NUMBER NOT NULL 
, ACTION_TYPE VARCHAR2(300 BYTE) NOT NULL 
, SLA_DAYS NUMBER 
, CUT_OFF_DATE DATE 
, LAST_UPDATED_BY VARCHAR2(50 BYTE) 
, LAST_UPDATED_DATE DATE 
, CREATED_DATE DATE 
, CREATED_BY VARCHAR2(50 BYTE) 
, CONSTRAINT ACTION_TYPE_MAINTENANCE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_CAN 
(
  CAN_ID NUMBER NOT NULL 
, FUND VARCHAR2(40 BYTE) 
, ALLOWANCE VARCHAR2(40 BYTE) 
, SUBALLOWANCE VARCHAR2(40 BYTE) 
, COST_CENTER VARCHAR2(40 BYTE) 
, FISCAL_YEAR VARCHAR2(4 BYTE) 
, FUND_DESC VARCHAR2(100 BYTE) 
, ALLOWANCE_DESC VARCHAR2(100 BYTE) 
, SUB_ALLOWANCE_DESC VARCHAR2(100 BYTE) 
, COST_CENTER_DESC VARCHAR2(100 BYTE) 
, CONSTRAINT AAP_CAN_PK PRIMARY KEY 
  (
    CAN_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE AAP_FUNDING_OBJECT 
(
  FUNDING_OBJECT_CLASS_ID NUMBER NOT NULL 
, FUNDING_OBJECT_CLASS VARCHAR2(100 BYTE) 
, CONSTRAINT AAP_FUNDING_OBJECT_PK PRIMARY KEY 
  (
    FUNDING_OBJECT_CLASS_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE AAP_REQUESTS
ADD CONSTRAINT REQUESTS_UK1 UNIQUE 
(
  CTR_LN_ITM_NO 
)
ENABLE;

ALTER TABLE AAP_NOTIFICATION
ADD CONSTRAINT AAP_NOTIFICATION_REQUESTS_FK1 FOREIGN KEY
(
  REQUEST_ID 
)
REFERENCES AAP_REQUESTS
(
  REQUEST_ID 
)
ENABLE;

ALTER TABLE AAP_POINT_OF_CONTACT
ADD CONSTRAINT POINT_OF_CONTACT_REQUESTS_FK1 FOREIGN KEY
(
  REQUEST_ID 
)
REFERENCES AAP_REQUESTS
(
  REQUEST_ID 
)
ENABLE;

ALTER TABLE AAP_DETAILED_EXPENSES
ADD CONSTRAINT DETAILED_EXPENSES_REQUEST_FK1 FOREIGN KEY
(
  REQUEST_ID 
)
REFERENCES AAP_REQUESTS
(
  REQUEST_ID 
)
ENABLE;
