package com.fda.aps.model.viewobject.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 03:04:39 EDT 2015
// ---------------------------------------------------------------------
public interface AapFundingObjectView extends ViewObject {
    void setbind_Type(String value);
}
