package com.fda.aps.model.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 16 12:45:41 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PointOfContactImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PocId {
            public Object get(PointOfContactImpl obj) {
                return obj.getPocId();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        PocFirstName {
            public Object get(PointOfContactImpl obj) {
                return obj.getPocFirstName();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setPocFirstName((String)value);
            }
        }
        ,
        PocLastName {
            public Object get(PointOfContactImpl obj) {
                return obj.getPocLastName();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setPocLastName((String)value);
            }
        }
        ,
        PocEmail {
            public Object get(PointOfContactImpl obj) {
                return obj.getPocEmail();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setPocEmail((String)value);
            }
        }
        ,
        PocTel {
            public Object get(PointOfContactImpl obj) {
                return obj.getPocTel();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setPocTel((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PointOfContactImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PointOfContactImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PointOfContactImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PointOfContactImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        RequestId {
            public Object get(PointOfContactImpl obj) {
                return obj.getRequestId();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setRequestId((Number)value);
            }
        }
        ,
        RequestsEntity {
            public Object get(PointOfContactImpl obj) {
                return obj.getRequestsEntity();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setRequestsEntity((RequestsEntityImpl)value);
            }
        }
        ,
        AapRequests {
            public Object get(PointOfContactImpl obj) {
                return obj.getAapRequests();
            }

            public void put(PointOfContactImpl obj, Object value) {
                obj.setAapRequests((AapRequestsImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PointOfContactImpl object);

        public abstract void put(PointOfContactImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int POCID = AttributesEnum.PocId.index();
    public static final int POCFIRSTNAME = AttributesEnum.PocFirstName.index();
    public static final int POCLASTNAME = AttributesEnum.PocLastName.index();
    public static final int POCEMAIL = AttributesEnum.PocEmail.index();
    public static final int POCTEL = AttributesEnum.PocTel.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int REQUESTSENTITY = AttributesEnum.RequestsEntity.index();
    public static final int AAPREQUESTS = AttributesEnum.AapRequests.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PointOfContactImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.fda.aps.model.entity.PointOfContact");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for PocId, using the alias name PocId.
     * @return the PocId
     */
    public Number getPocId() {
        return (Number)getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocId.
     * @param value value to set the PocId
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * Gets the attribute value for PocFirstName, using the alias name PocFirstName.
     * @return the PocFirstName
     */
    public String getPocFirstName() {
        return (String)getAttributeInternal(POCFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocFirstName.
     * @param value value to set the PocFirstName
     */
    public void setPocFirstName(String value) {
        setAttributeInternal(POCFIRSTNAME, value);
    }

    /**
     * Gets the attribute value for PocLastName, using the alias name PocLastName.
     * @return the PocLastName
     */
    public String getPocLastName() {
        return (String)getAttributeInternal(POCLASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocLastName.
     * @param value value to set the PocLastName
     */
    public void setPocLastName(String value) {
        setAttributeInternal(POCLASTNAME, value);
    }

    /**
     * Gets the attribute value for PocEmail, using the alias name PocEmail.
     * @return the PocEmail
     */
    public String getPocEmail() {
        return (String)getAttributeInternal(POCEMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocEmail.
     * @param value value to set the PocEmail
     */
    public void setPocEmail(String value) {
        setAttributeInternal(POCEMAIL, value);
    }

    /**
     * Gets the attribute value for PocTel, using the alias name PocTel.
     * @return the PocTel
     */
    public String getPocTel() {
        return (String)getAttributeInternal(POCTEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocTel.
     * @param value value to set the PocTel
     */
    public void setPocTel(String value) {
        setAttributeInternal(POCTEL, value);
    }


    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for RequestId, using the alias name RequestId.
     * @return the RequestId
     */
    public Number getRequestId() {
        return (Number)getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestId.
     * @param value value to set the RequestId
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity RequestsEntityImpl.
     */
    public RequestsEntityImpl getRequestsEntity() {
        return (RequestsEntityImpl)getAttributeInternal(REQUESTSENTITY);
    }

    /**
     * Sets <code>value</code> as the associated entity RequestsEntityImpl.
     */
    public void setRequestsEntity(RequestsEntityImpl value) {
        setAttributeInternal(REQUESTSENTITY, value);
    }


    /**
     * @return the associated entity AapRequestsImpl.
     */
    public AapRequestsImpl getAapRequests() {
        return (AapRequestsImpl)getAttributeInternal(AAPREQUESTS);
    }

    /**
     * Sets <code>value</code> as the associated entity AapRequestsImpl.
     */
    public void setAapRequests(AapRequestsImpl value) {
        setAttributeInternal(AAPREQUESTS, value);
    }

    /**
     * @param pocId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number pocId) {
        return new Key(new Object[]{pocId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        SequenceImpl seq = new SequenceImpl("POC_SEQ", getDBTransaction());
        Number pocNo = seq.getSequenceNumber();
        setPocId(pocNo);

        super.create(attributeList);
    }
}
