package com.fda.aps.model.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 24 18:24:03 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestsEntityImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        
        
        super.doDML(operation, e);
        
        System.err.println("test doDML");
        
//        if (operation == 1){
//                EntityDefImpl notificationDef = AapNotificationImpl.getDefinitionObject();
//                AapNotificationImpl newNotification = (AapNotificationImpl)notificationDef.createInstance2(getDBTransaction(), null);
//                
//                newNotification.setSubmittedFrom("");
//                newNotification.setSubmittedTo("");
//                newNotification.setRequestId(this.getRequestId());
//                //newNotification.setNotificationId(value);
//            
//        }
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CtrLnItmNo {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCtrLnItmNo();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setCtrLnItmNo((String)value);
            }
        }
        ,
        AcquisitionStatus {
            public Object get(RequestsEntityImpl obj) {
                return obj.getAcquisitionStatus();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAcquisitionStatus((String)value);
            }
        }
        ,
        PriorityLevel {
            public Object get(RequestsEntityImpl obj) {
                return obj.getPriorityLevel();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setPriorityLevel((String)value);
            }
        }
        ,
        RecurringItem {
            public Object get(RequestsEntityImpl obj) {
                return obj.getRecurringItem();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setRecurringItem((String)value);
            }
        }
        ,
        ZeroDollarReqn {
            public Object get(RequestsEntityImpl obj) {
                return obj.getZeroDollarReqn();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setZeroDollarReqn((String)value);
            }
        }
        ,
        RequisitionNo {
            public Object get(RequestsEntityImpl obj) {
                return obj.getRequisitionNo();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setRequisitionNo((String)value);
            }
        }
        ,
        ExistingDocNo {
            public Object get(RequestsEntityImpl obj) {
                return obj.getExistingDocNo();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setExistingDocNo((String)value);
            }
        }
        ,
        ReleaseNumber {
            public Object get(RequestsEntityImpl obj) {
                return obj.getReleaseNumber();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setReleaseNumber((String)value);
            }
        }
        ,
        RequirementType {
            public Object get(RequestsEntityImpl obj) {
                return obj.getRequirementType();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setRequirementType((String)value);
            }
        }
        ,
        OptionYrExercise {
            public Object get(RequestsEntityImpl obj) {
                return obj.getOptionYrExercise();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setOptionYrExercise((String)value);
            }
        }
        ,
        DetailedDescription {
            public Object get(RequestsEntityImpl obj) {
                return obj.getDetailedDescription();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setDetailedDescription((String)value);
            }
        }
        ,
        RequiredAwardDate {
            public Object get(RequestsEntityImpl obj) {
                return obj.getRequiredAwardDate();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setRequiredAwardDate((Date)value);
            }
        }
        ,
        CurrYrPopEndDate {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCurrYrPopEndDate();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setCurrYrPopEndDate((Date)value);
            }
        }
        ,
        AnticipatedActionType {
            public Object get(RequestsEntityImpl obj) {
                return obj.getAnticipatedActionType();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAnticipatedActionType((String)value);
            }
        }
        ,
        PotentialContractType {
            public Object get(RequestsEntityImpl obj) {
                return obj.getPotentialContractType();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setPotentialContractType((String)value);
            }
        }
        ,
        CommodityType {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCommodityType();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setCommodityType((String)value);
            }
        }
        ,
        Column1 {
            public Object get(RequestsEntityImpl obj) {
                return obj.getColumn1();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setColumn1((String)value);
            }
        }
        ,
        AnticipatedAcquisitionMethod {
            public Object get(RequestsEntityImpl obj) {
                return obj.getAnticipatedAcquisitionMethod();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAnticipatedAcquisitionMethod((String)value);
            }
        }
        ,
        ProductServiceCode {
            public Object get(RequestsEntityImpl obj) {
                return obj.getProductServiceCode();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setProductServiceCode((String)value);
            }
        }
        ,
        NaicsCode {
            public Object get(RequestsEntityImpl obj) {
                return obj.getNaicsCode();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setNaicsCode((String)value);
            }
        }
        ,
        EstimatedTotalProjValue {
            public Object get(RequestsEntityImpl obj) {
                return obj.getEstimatedTotalProjValue();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setEstimatedTotalProjValue((String)value);
            }
        }
        ,
        TotalDlarsForCurtFy {
            public Object get(RequestsEntityImpl obj) {
                return obj.getTotalDlarsForCurtFy();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setTotalDlarsForCurtFy((Number)value);
            }
        }
        ,
        ProjectPopStartDate {
            public Object get(RequestsEntityImpl obj) {
                return obj.getProjectPopStartDate();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setProjectPopStartDate((Date)value);
            }
        }
        ,
        ProjectPopEndDate {
            public Object get(RequestsEntityImpl obj) {
                return obj.getProjectPopEndDate();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setProjectPopEndDate((Date)value);
            }
        }
        ,
        AnticipatedPop {
            public Object get(RequestsEntityImpl obj) {
                return obj.getAnticipatedPop();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAnticipatedPop((String)value);
            }
        }
        ,
        CollaborationFlag {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCollaborationFlag();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setCollaborationFlag((String)value);
            }
        }
        ,
        CollaborationItemNo {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCollaborationItemNo();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setCollaborationItemNo((String)value);
            }
        }
        ,
        LeadMngCenter {
            public Object get(RequestsEntityImpl obj) {
                return obj.getLeadMngCenter();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setLeadMngCenter((String)value);
            }
        }
        ,
        OwnerNmTelNo {
            public Object get(RequestsEntityImpl obj) {
                return obj.getOwnerNmTelNo();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setOwnerNmTelNo((String)value);
            }
        }
        ,
        EstimatedRfaRelDate {
            public Object get(RequestsEntityImpl obj) {
                return obj.getEstimatedRfaRelDate();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setEstimatedRfaRelDate((Date)value);
            }
        }
        ,
        GrantsCommodity {
            public Object get(RequestsEntityImpl obj) {
                return obj.getGrantsCommodity();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setGrantsCommodity((String)value);
            }
        }
        ,
        NciboardReviewRequired {
            public Object get(RequestsEntityImpl obj) {
                return obj.getNciboardReviewRequired();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setNciboardReviewRequired((String)value);
            }
        }
        ,
        AnticipatedNoOfAwards {
            public Object get(RequestsEntityImpl obj) {
                return obj.getAnticipatedNoOfAwards();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAnticipatedNoOfAwards((String)value);
            }
        }
        ,
        ExistingIaaNumber {
            public Object get(RequestsEntityImpl obj) {
                return obj.getExistingIaaNumber();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setExistingIaaNumber((String)value);
            }
        }
        ,
        Purpose {
            public Object get(RequestsEntityImpl obj) {
                return obj.getPurpose();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setPurpose((String)value);
            }
        }
        ,
        EstimatedNumberOfActions {
            public Object get(RequestsEntityImpl obj) {
                return obj.getEstimatedNumberOfActions();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setEstimatedNumberOfActions((String)value);
            }
        }
        ,
        ServiceOrReimbursable {
            public Object get(RequestsEntityImpl obj) {
                return obj.getServiceOrReimbursable();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setServiceOrReimbursable((String)value);
            }
        }
        ,
        ReimbursableAmt {
            public Object get(RequestsEntityImpl obj) {
                return obj.getReimbursableAmt();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setReimbursableAmt((String)value);
            }
        }
        ,
        ReimbursableAgency {
            public Object get(RequestsEntityImpl obj) {
                return obj.getReimbursableAgency();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setReimbursableAgency((String)value);
            }
        }
        ,
        SubmitFlag {
            public Object get(RequestsEntityImpl obj) {
                return obj.getSubmitFlag();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setSubmitFlag((String)value);
            }
        }
        ,
        CenterId {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCenterId();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setCenterId((String)value);
            }
        }
        ,
        RequestId {
            public Object get(RequestsEntityImpl obj) {
                return obj.getRequestId();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setRequestId((Number)value);
            }
        }
        ,
        FiscalYear {
            public Object get(RequestsEntityImpl obj) {
                return obj.getFiscalYear();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setFiscalYear((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedDate {
            public Object get(RequestsEntityImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(RequestsEntityImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(RequestsEntityImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PointOfContact {
            public Object get(RequestsEntityImpl obj) {
                return obj.getPointOfContact();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AapNotification {
            public Object get(RequestsEntityImpl obj) {
                return obj.getAapNotification();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AapDetailedExpenses {
            public Object get(RequestsEntityImpl obj) {
                return obj.getAapDetailedExpenses();
            }

            public void put(RequestsEntityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(RequestsEntityImpl object);

        public abstract void put(RequestsEntityImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CTRLNITMNO = AttributesEnum.CtrLnItmNo.index();
    public static final int ACQUISITIONSTATUS = AttributesEnum.AcquisitionStatus.index();
    public static final int PRIORITYLEVEL = AttributesEnum.PriorityLevel.index();
    public static final int RECURRINGITEM = AttributesEnum.RecurringItem.index();
    public static final int ZERODOLLARREQN = AttributesEnum.ZeroDollarReqn.index();
    public static final int REQUISITIONNO = AttributesEnum.RequisitionNo.index();
    public static final int EXISTINGDOCNO = AttributesEnum.ExistingDocNo.index();
    public static final int RELEASENUMBER = AttributesEnum.ReleaseNumber.index();
    public static final int REQUIREMENTTYPE = AttributesEnum.RequirementType.index();
    public static final int OPTIONYREXERCISE = AttributesEnum.OptionYrExercise.index();
    public static final int DETAILEDDESCRIPTION = AttributesEnum.DetailedDescription.index();
    public static final int REQUIREDAWARDDATE = AttributesEnum.RequiredAwardDate.index();
    public static final int CURRYRPOPENDDATE = AttributesEnum.CurrYrPopEndDate.index();
    public static final int ANTICIPATEDACTIONTYPE = AttributesEnum.AnticipatedActionType.index();
    public static final int POTENTIALCONTRACTTYPE = AttributesEnum.PotentialContractType.index();
    public static final int COMMODITYTYPE = AttributesEnum.CommodityType.index();
    public static final int COLUMN1 = AttributesEnum.Column1.index();
    public static final int ANTICIPATEDACQUISITIONMETHOD = AttributesEnum.AnticipatedAcquisitionMethod.index();
    public static final int PRODUCTSERVICECODE = AttributesEnum.ProductServiceCode.index();
    public static final int NAICSCODE = AttributesEnum.NaicsCode.index();
    public static final int ESTIMATEDTOTALPROJVALUE = AttributesEnum.EstimatedTotalProjValue.index();
    public static final int TOTALDLARSFORCURTFY = AttributesEnum.TotalDlarsForCurtFy.index();
    public static final int PROJECTPOPSTARTDATE = AttributesEnum.ProjectPopStartDate.index();
    public static final int PROJECTPOPENDDATE = AttributesEnum.ProjectPopEndDate.index();
    public static final int ANTICIPATEDPOP = AttributesEnum.AnticipatedPop.index();
    public static final int COLLABORATIONFLAG = AttributesEnum.CollaborationFlag.index();
    public static final int COLLABORATIONITEMNO = AttributesEnum.CollaborationItemNo.index();
    public static final int LEADMNGCENTER = AttributesEnum.LeadMngCenter.index();
    public static final int OWNERNMTELNO = AttributesEnum.OwnerNmTelNo.index();
    public static final int ESTIMATEDRFARELDATE = AttributesEnum.EstimatedRfaRelDate.index();
    public static final int GRANTSCOMMODITY = AttributesEnum.GrantsCommodity.index();
    public static final int NCIBOARDREVIEWREQUIRED = AttributesEnum.NciboardReviewRequired.index();
    public static final int ANTICIPATEDNOOFAWARDS = AttributesEnum.AnticipatedNoOfAwards.index();
    public static final int EXISTINGIAANUMBER = AttributesEnum.ExistingIaaNumber.index();
    public static final int PURPOSE = AttributesEnum.Purpose.index();
    public static final int ESTIMATEDNUMBEROFACTIONS = AttributesEnum.EstimatedNumberOfActions.index();
    public static final int SERVICEORREIMBURSABLE = AttributesEnum.ServiceOrReimbursable.index();
    public static final int REIMBURSABLEAMT = AttributesEnum.ReimbursableAmt.index();
    public static final int REIMBURSABLEAGENCY = AttributesEnum.ReimbursableAgency.index();
    public static final int SUBMITFLAG = AttributesEnum.SubmitFlag.index();
    public static final int CENTERID = AttributesEnum.CenterId.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int FISCALYEAR = AttributesEnum.FiscalYear.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int POINTOFCONTACT = AttributesEnum.PointOfContact.index();
    public static final int AAPNOTIFICATION = AttributesEnum.AapNotification.index();
    public static final int AAPDETAILEDEXPENSES = AttributesEnum.AapDetailedExpenses.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RequestsEntityImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.fda.aps.model.entity.RequestsEntity");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for CtrLnItmNo, using the alias name CtrLnItmNo.
     * @return the CtrLnItmNo
     */
    public String getCtrLnItmNo() {
        return (String)getAttributeInternal(CTRLNITMNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CtrLnItmNo.
     * @param value value to set the CtrLnItmNo
     */
    public void setCtrLnItmNo(String value) {
        setAttributeInternal(CTRLNITMNO, value);
    }

    /**
     * Gets the attribute value for AcquisitionStatus, using the alias name AcquisitionStatus.
     * @return the AcquisitionStatus
     */
    public String getAcquisitionStatus() {
        return (String)getAttributeInternal(ACQUISITIONSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AcquisitionStatus.
     * @param value value to set the AcquisitionStatus
     */
    public void setAcquisitionStatus(String value) {
        setAttributeInternal(ACQUISITIONSTATUS, value);
    }

    /**
     * Gets the attribute value for PriorityLevel, using the alias name PriorityLevel.
     * @return the PriorityLevel
     */
    public String getPriorityLevel() {
        return (String)getAttributeInternal(PRIORITYLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for PriorityLevel.
     * @param value value to set the PriorityLevel
     */
    public void setPriorityLevel(String value) {
        setAttributeInternal(PRIORITYLEVEL, value);
    }

    /**
     * Gets the attribute value for RecurringItem, using the alias name RecurringItem.
     * @return the RecurringItem
     */
    public String getRecurringItem() {
        return (String)getAttributeInternal(RECURRINGITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecurringItem.
     * @param value value to set the RecurringItem
     */
    public void setRecurringItem(String value) {
        setAttributeInternal(RECURRINGITEM, value);
    }

    /**
     * Gets the attribute value for ZeroDollarReqn, using the alias name ZeroDollarReqn.
     * @return the ZeroDollarReqn
     */
    public String getZeroDollarReqn() {
        return (String)getAttributeInternal(ZERODOLLARREQN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ZeroDollarReqn.
     * @param value value to set the ZeroDollarReqn
     */
    public void setZeroDollarReqn(String value) {
        setAttributeInternal(ZERODOLLARREQN, value);
    }

    /**
     * Gets the attribute value for RequisitionNo, using the alias name RequisitionNo.
     * @return the RequisitionNo
     */
    public String getRequisitionNo() {
        return (String)getAttributeInternal(REQUISITIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequisitionNo.
     * @param value value to set the RequisitionNo
     */
    public void setRequisitionNo(String value) {
        setAttributeInternal(REQUISITIONNO, value);
    }

    /**
     * Gets the attribute value for ExistingDocNo, using the alias name ExistingDocNo.
     * @return the ExistingDocNo
     */
    public String getExistingDocNo() {
        return (String)getAttributeInternal(EXISTINGDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExistingDocNo.
     * @param value value to set the ExistingDocNo
     */
    public void setExistingDocNo(String value) {
        setAttributeInternal(EXISTINGDOCNO, value);
    }

    /**
     * Gets the attribute value for ReleaseNumber, using the alias name ReleaseNumber.
     * @return the ReleaseNumber
     */
    public String getReleaseNumber() {
        return (String)getAttributeInternal(RELEASENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseNumber.
     * @param value value to set the ReleaseNumber
     */
    public void setReleaseNumber(String value) {
        setAttributeInternal(RELEASENUMBER, value);
    }

    /**
     * Gets the attribute value for RequirementType, using the alias name RequirementType.
     * @return the RequirementType
     */
    public String getRequirementType() {
        return (String)getAttributeInternal(REQUIREMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequirementType.
     * @param value value to set the RequirementType
     */
    public void setRequirementType(String value) {
        setAttributeInternal(REQUIREMENTTYPE, value);
    }

    /**
     * Gets the attribute value for OptionYrExercise, using the alias name OptionYrExercise.
     * @return the OptionYrExercise
     */
    public String getOptionYrExercise() {
        return (String)getAttributeInternal(OPTIONYREXERCISE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OptionYrExercise.
     * @param value value to set the OptionYrExercise
     */
    public void setOptionYrExercise(String value) {
        setAttributeInternal(OPTIONYREXERCISE, value);
    }

    /**
     * Gets the attribute value for DetailedDescription, using the alias name DetailedDescription.
     * @return the DetailedDescription
     */
    public String getDetailedDescription() {
        return (String)getAttributeInternal(DETAILEDDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailedDescription.
     * @param value value to set the DetailedDescription
     */
    public void setDetailedDescription(String value) {
        setAttributeInternal(DETAILEDDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for RequiredAwardDate, using the alias name RequiredAwardDate.
     * @return the RequiredAwardDate
     */
    public Date getRequiredAwardDate() {
        return (Date)getAttributeInternal(REQUIREDAWARDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequiredAwardDate.
     * @param value value to set the RequiredAwardDate
     */
    public void setRequiredAwardDate(Date value) {
        setAttributeInternal(REQUIREDAWARDDATE, value);
    }

    /**
     * Gets the attribute value for CurrYrPopEndDate, using the alias name CurrYrPopEndDate.
     * @return the CurrYrPopEndDate
     */
    public Date getCurrYrPopEndDate() {
        return (Date)getAttributeInternal(CURRYRPOPENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrYrPopEndDate.
     * @param value value to set the CurrYrPopEndDate
     */
    public void setCurrYrPopEndDate(Date value) {
        setAttributeInternal(CURRYRPOPENDDATE, value);
    }

    /**
     * Gets the attribute value for AnticipatedActionType, using the alias name AnticipatedActionType.
     * @return the AnticipatedActionType
     */
    public String getAnticipatedActionType() {
        return (String)getAttributeInternal(ANTICIPATEDACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AnticipatedActionType.
     * @param value value to set the AnticipatedActionType
     */
    public void setAnticipatedActionType(String value) {
        setAttributeInternal(ANTICIPATEDACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for PotentialContractType, using the alias name PotentialContractType.
     * @return the PotentialContractType
     */
    public String getPotentialContractType() {
        return (String)getAttributeInternal(POTENTIALCONTRACTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PotentialContractType.
     * @param value value to set the PotentialContractType
     */
    public void setPotentialContractType(String value) {
        setAttributeInternal(POTENTIALCONTRACTTYPE, value);
    }

    /**
     * Gets the attribute value for CommodityType, using the alias name CommodityType.
     * @return the CommodityType
     */
    public String getCommodityType() {
        return (String)getAttributeInternal(COMMODITYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommodityType.
     * @param value value to set the CommodityType
     */
    public void setCommodityType(String value) {
        setAttributeInternal(COMMODITYTYPE, value);
    }

    /**
     * Gets the attribute value for Column1, using the alias name Column1.
     * @return the Column1
     */
    public String getColumn1() {
        return (String)getAttributeInternal(COLUMN1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Column1.
     * @param value value to set the Column1
     */
    public void setColumn1(String value) {
        setAttributeInternal(COLUMN1, value);
    }

    /**
     * Gets the attribute value for AnticipatedAcquisitionMethod, using the alias name AnticipatedAcquisitionMethod.
     * @return the AnticipatedAcquisitionMethod
     */
    public String getAnticipatedAcquisitionMethod() {
        return (String)getAttributeInternal(ANTICIPATEDACQUISITIONMETHOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AnticipatedAcquisitionMethod.
     * @param value value to set the AnticipatedAcquisitionMethod
     */
    public void setAnticipatedAcquisitionMethod(String value) {
        setAttributeInternal(ANTICIPATEDACQUISITIONMETHOD, value);
    }

    /**
     * Gets the attribute value for ProductServiceCode, using the alias name ProductServiceCode.
     * @return the ProductServiceCode
     */
    public String getProductServiceCode() {
        return (String)getAttributeInternal(PRODUCTSERVICECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductServiceCode.
     * @param value value to set the ProductServiceCode
     */
    public void setProductServiceCode(String value) {
        setAttributeInternal(PRODUCTSERVICECODE, value);
    }

    /**
     * Gets the attribute value for NaicsCode, using the alias name NaicsCode.
     * @return the NaicsCode
     */
    public String getNaicsCode() {
        return (String)getAttributeInternal(NAICSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NaicsCode.
     * @param value value to set the NaicsCode
     */
    public void setNaicsCode(String value) {
        setAttributeInternal(NAICSCODE, value);
    }

    /**
     * Gets the attribute value for EstimatedTotalProjValue, using the alias name EstimatedTotalProjValue.
     * @return the EstimatedTotalProjValue
     */
    public String getEstimatedTotalProjValue() {
        return (String)getAttributeInternal(ESTIMATEDTOTALPROJVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstimatedTotalProjValue.
     * @param value value to set the EstimatedTotalProjValue
     */
    public void setEstimatedTotalProjValue(String value) {
        setAttributeInternal(ESTIMATEDTOTALPROJVALUE, value);
    }

    /**
     * Gets the attribute value for TotalDlarsForCurtFy, using the alias name TotalDlarsForCurtFy.
     * @return the TotalDlarsForCurtFy
     */
    public Number getTotalDlarsForCurtFy() {
        return (Number)getAttributeInternal(TOTALDLARSFORCURTFY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalDlarsForCurtFy.
     * @param value value to set the TotalDlarsForCurtFy
     */
    public void setTotalDlarsForCurtFy(Number value) {
        setAttributeInternal(TOTALDLARSFORCURTFY, value);
    }

    /**
     * Gets the attribute value for ProjectPopStartDate, using the alias name ProjectPopStartDate.
     * @return the ProjectPopStartDate
     */
    public Date getProjectPopStartDate() {
        return (Date)getAttributeInternal(PROJECTPOPSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectPopStartDate.
     * @param value value to set the ProjectPopStartDate
     */
    public void setProjectPopStartDate(Date value) {
        setAttributeInternal(PROJECTPOPSTARTDATE, value);
    }

    /**
     * Gets the attribute value for ProjectPopEndDate, using the alias name ProjectPopEndDate.
     * @return the ProjectPopEndDate
     */
    public Date getProjectPopEndDate() {
        return (Date)getAttributeInternal(PROJECTPOPENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectPopEndDate.
     * @param value value to set the ProjectPopEndDate
     */
    public void setProjectPopEndDate(Date value) {
        setAttributeInternal(PROJECTPOPENDDATE, value);
    }

    /**
     * Gets the attribute value for AnticipatedPop, using the alias name AnticipatedPop.
     * @return the AnticipatedPop
     */
    public String getAnticipatedPop() {
        return (String)getAttributeInternal(ANTICIPATEDPOP);
    }

    /**
     * Sets <code>value</code> as the attribute value for AnticipatedPop.
     * @param value value to set the AnticipatedPop
     */
    public void setAnticipatedPop(String value) {
        setAttributeInternal(ANTICIPATEDPOP, value);
    }

    /**
     * Gets the attribute value for CollaborationFlag, using the alias name CollaborationFlag.
     * @return the CollaborationFlag
     */
    public String getCollaborationFlag() {
        return (String)getAttributeInternal(COLLABORATIONFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for CollaborationFlag.
     * @param value value to set the CollaborationFlag
     */
    public void setCollaborationFlag(String value) {
        setAttributeInternal(COLLABORATIONFLAG, value);
    }

    /**
     * Gets the attribute value for CollaborationItemNo, using the alias name CollaborationItemNo.
     * @return the CollaborationItemNo
     */
    public String getCollaborationItemNo() {
        return (String)getAttributeInternal(COLLABORATIONITEMNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CollaborationItemNo.
     * @param value value to set the CollaborationItemNo
     */
    public void setCollaborationItemNo(String value) {
        setAttributeInternal(COLLABORATIONITEMNO, value);
    }

    /**
     * Gets the attribute value for LeadMngCenter, using the alias name LeadMngCenter.
     * @return the LeadMngCenter
     */
    public String getLeadMngCenter() {
        return (String)getAttributeInternal(LEADMNGCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeadMngCenter.
     * @param value value to set the LeadMngCenter
     */
    public void setLeadMngCenter(String value) {
        setAttributeInternal(LEADMNGCENTER, value);
    }

    /**
     * Gets the attribute value for OwnerNmTelNo, using the alias name OwnerNmTelNo.
     * @return the OwnerNmTelNo
     */
    public String getOwnerNmTelNo() {
        return (String)getAttributeInternal(OWNERNMTELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for OwnerNmTelNo.
     * @param value value to set the OwnerNmTelNo
     */
    public void setOwnerNmTelNo(String value) {
        setAttributeInternal(OWNERNMTELNO, value);
    }

    /**
     * Gets the attribute value for EstimatedRfaRelDate, using the alias name EstimatedRfaRelDate.
     * @return the EstimatedRfaRelDate
     */
    public Date getEstimatedRfaRelDate() {
        return (Date)getAttributeInternal(ESTIMATEDRFARELDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstimatedRfaRelDate.
     * @param value value to set the EstimatedRfaRelDate
     */
    public void setEstimatedRfaRelDate(Date value) {
        setAttributeInternal(ESTIMATEDRFARELDATE, value);
    }

    /**
     * Gets the attribute value for GrantsCommodity, using the alias name GrantsCommodity.
     * @return the GrantsCommodity
     */
    public String getGrantsCommodity() {
        return (String)getAttributeInternal(GRANTSCOMMODITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrantsCommodity.
     * @param value value to set the GrantsCommodity
     */
    public void setGrantsCommodity(String value) {
        setAttributeInternal(GRANTSCOMMODITY, value);
    }

    /**
     * Gets the attribute value for NciboardReviewRequired, using the alias name NciboardReviewRequired.
     * @return the NciboardReviewRequired
     */
    public String getNciboardReviewRequired() {
        return (String)getAttributeInternal(NCIBOARDREVIEWREQUIRED);
    }

    /**
     * Sets <code>value</code> as the attribute value for NciboardReviewRequired.
     * @param value value to set the NciboardReviewRequired
     */
    public void setNciboardReviewRequired(String value) {
        setAttributeInternal(NCIBOARDREVIEWREQUIRED, value);
    }

    /**
     * Gets the attribute value for AnticipatedNoOfAwards, using the alias name AnticipatedNoOfAwards.
     * @return the AnticipatedNoOfAwards
     */
    public String getAnticipatedNoOfAwards() {
        return (String)getAttributeInternal(ANTICIPATEDNOOFAWARDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AnticipatedNoOfAwards.
     * @param value value to set the AnticipatedNoOfAwards
     */
    public void setAnticipatedNoOfAwards(String value) {
        setAttributeInternal(ANTICIPATEDNOOFAWARDS, value);
    }

    /**
     * Gets the attribute value for ExistingIaaNumber, using the alias name ExistingIaaNumber.
     * @return the ExistingIaaNumber
     */
    public String getExistingIaaNumber() {
        return (String)getAttributeInternal(EXISTINGIAANUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExistingIaaNumber.
     * @param value value to set the ExistingIaaNumber
     */
    public void setExistingIaaNumber(String value) {
        setAttributeInternal(EXISTINGIAANUMBER, value);
    }

    /**
     * Gets the attribute value for Purpose, using the alias name Purpose.
     * @return the Purpose
     */
    public String getPurpose() {
        return (String)getAttributeInternal(PURPOSE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Purpose.
     * @param value value to set the Purpose
     */
    public void setPurpose(String value) {
        setAttributeInternal(PURPOSE, value);
    }

    /**
     * Gets the attribute value for EstimatedNumberOfActions, using the alias name EstimatedNumberOfActions.
     * @return the EstimatedNumberOfActions
     */
    public String getEstimatedNumberOfActions() {
        return (String)getAttributeInternal(ESTIMATEDNUMBEROFACTIONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstimatedNumberOfActions.
     * @param value value to set the EstimatedNumberOfActions
     */
    public void setEstimatedNumberOfActions(String value) {
        setAttributeInternal(ESTIMATEDNUMBEROFACTIONS, value);
    }

    /**
     * Gets the attribute value for ServiceOrReimbursable, using the alias name ServiceOrReimbursable.
     * @return the ServiceOrReimbursable
     */
    public String getServiceOrReimbursable() {
        return (String)getAttributeInternal(SERVICEORREIMBURSABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ServiceOrReimbursable.
     * @param value value to set the ServiceOrReimbursable
     */
    public void setServiceOrReimbursable(String value) {
        setAttributeInternal(SERVICEORREIMBURSABLE, value);
    }

    /**
     * Gets the attribute value for ReimbursableAmt, using the alias name ReimbursableAmt.
     * @return the ReimbursableAmt
     */
    public String getReimbursableAmt() {
        return (String)getAttributeInternal(REIMBURSABLEAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReimbursableAmt.
     * @param value value to set the ReimbursableAmt
     */
    public void setReimbursableAmt(String value) {
        setAttributeInternal(REIMBURSABLEAMT, value);
    }

    /**
     * Gets the attribute value for ReimbursableAgency, using the alias name ReimbursableAgency.
     * @return the ReimbursableAgency
     */
    public String getReimbursableAgency() {
        return (String)getAttributeInternal(REIMBURSABLEAGENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReimbursableAgency.
     * @param value value to set the ReimbursableAgency
     */
    public void setReimbursableAgency(String value) {
        setAttributeInternal(REIMBURSABLEAGENCY, value);
    }

    /**
     * Gets the attribute value for SubmitFlag, using the alias name SubmitFlag.
     * @return the SubmitFlag
     */
    public String getSubmitFlag() {
        return (String)getAttributeInternal(SUBMITFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmitFlag.
     * @param value value to set the SubmitFlag
     */
    public void setSubmitFlag(String value) {
        setAttributeInternal(SUBMITFLAG, value);
    }


    /**
     * Gets the attribute value for CenterId, using the alias name CenterId.
     * @return the CenterId
     */
    public String getCenterId() {
        return (String)getAttributeInternal(CENTERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CenterId.
     * @param value value to set the CenterId
     */
    public void setCenterId(String value) {
        setAttributeInternal(CENTERID, value);
    }


    /**
     * Gets the attribute value for RequestId, using the alias name RequestId.
     * @return the RequestId
     */
    public Number getRequestId() {
        return (Number)getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestId.
     * @param value value to set the RequestId
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for FiscalYear, using the alias name FiscalYear.
     * @return the FiscalYear
     */
    public String getFiscalYear() {
        return (String)getAttributeInternal(FISCALYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for FiscalYear.
     * @param value value to set the FiscalYear
     */
    public void setFiscalYear(String value) {
        setAttributeInternal(FISCALYEAR, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPointOfContact() {
        return (RowIterator)getAttributeInternal(POINTOFCONTACT);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAapNotification() {
        return (RowIterator)getAttributeInternal(AAPNOTIFICATION);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAapDetailedExpenses() {
        return (RowIterator)getAttributeInternal(AAPDETAILEDEXPENSES);
    }

    /**
     * @param requestId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number requestId) {
        return new Key(new Object[]{requestId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        SequenceImpl seq = new SequenceImpl("REQUEST_SEQ", getDBTransaction());
        Number reqNo = seq.getSequenceNumber();
        setRequestId(reqNo);
        super.create(attributeList);
    }
}
