package com.fda.aps.model.viewobject;

import com.fda.aps.model.viewobject.common.AapFundingObjectView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 03:02:46 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AapFundingObjectViewImpl extends ViewObjectImpl implements AapFundingObjectView {
    /**
     * This is the default constructor (do not remove).
     */
    public AapFundingObjectViewImpl() {
    }

    /**
     * Returns the bind variable value for bind_Type.
     * @return bind variable value for bind_Type
     */
    public String getbind_Type() {
        return (String)getNamedWhereClauseParam("bind_Type");
    }

    /**
     * Sets <code>value</code> for bind variable bind_Type.
     * @param value value to bind as bind_Type
     */
    public void setbind_Type(String value) {
        //setNamedWhereClauseParam("bind_Type", value);
        ensureVariableManager().setVariableValue("bind_Type", value);
        executeQuery();
    }
}
