package com.fda.aps.model.viewobject.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 22:16:25 EDT 2015
// ---------------------------------------------------------------------
public interface APSSearchView extends ViewObject {
    void setbind_UserCenter(String value);
}
