package com.fda.aps.model.viewobject;

import com.fda.aps.model.viewobject.common.APSSearchView;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 22:13:44 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class APSSearchViewImpl extends ViewObjectImpl implements APSSearchView {
    /**
     * This is the default constructor (do not remove).
     */
    public APSSearchViewImpl() {
    }

    /**
     * Returns the variable value for bindCenter.
     * @return variable value for bindCenter
     */
    public String getbindCenter() {
        return (String)ensureVariableManager().getVariableValue("bindCenter");
    }

    /**
     * Sets <code>value</code> for variable bindCenter.
     * @param value value to bind as bindCenter
     */
    public void setbindCenter(String value) {
        ensureVariableManager().setVariableValue("bindCenter", value);
    }

    /**
     * Returns the variable value for bindCenterLineNo.
     * @return variable value for bindCenterLineNo
     */
    public String getbindCenterLineNo() {
        return (String)ensureVariableManager().getVariableValue("bindCenterLineNo");
    }

    /**
     * Sets <code>value</code> for variable bindCenterLineNo.
     * @param value value to bind as bindCenterLineNo
     */
    public void setbindCenterLineNo(String value) {
        ensureVariableManager().setVariableValue("bindCenterLineNo", value);
    }

    /**
     * Returns the variable value for bindDocNo.
     * @return variable value for bindDocNo
     */
    public String getbindDocNo() {
        return (String)ensureVariableManager().getVariableValue("bindDocNo");
    }

    /**
     * Sets <code>value</code> for variable bindDocNo.
     * @param value value to bind as bindDocNo
     */
    public void setbindDocNo(String value) {
        ensureVariableManager().setVariableValue("bindDocNo", value);
    }

    /**
     * Returns the variable value for bindDescription.
     * @return variable value for bindDescription
     */
    public String getbindDescription() {
        return (String)ensureVariableManager().getVariableValue("bindDescription");
    }

    /**
     * Sets <code>value</code> for variable bindDescription.
     * @param value value to bind as bindDescription
     */
    public void setbindDescription(String value) {
        ensureVariableManager().setVariableValue("bindDescription", value);
    }

    /**
     * Returns the variable value for bindAwardDate.
     * @return variable value for bindAwardDate
     */
    public Date getbindAwardDate() {
        return (Date)ensureVariableManager().getVariableValue("bindAwardDate");
    }

    /**
     * Sets <code>value</code> for variable bindAwardDate.
     * @param value value to bind as bindAwardDate
     */
    public void setbindAwardDate(Date value) {
        ensureVariableManager().setVariableValue("bindAwardDate", value);
    }

    /**
     * Returns the variable value for bindRequisitionNo.
     * @return variable value for bindRequisitionNo
     */
    public String getbindRequisitionNo() {
        return (String)ensureVariableManager().getVariableValue("bindRequisitionNo");
    }

    /**
     * Sets <code>value</code> for variable bindRequisitionNo.
     * @param value value to bind as bindRequisitionNo
     */
    public void setbindRequisitionNo(String value) {
        ensureVariableManager().setVariableValue("bindRequisitionNo", value);
    }

    /**
     * Returns the variable value for bind_status.
     * @return variable value for bind_status
     */
    public String getbind_status() {
        return (String)ensureVariableManager().getVariableValue("bind_status");
    }

    /**
     * Sets <code>value</code> for variable bind_status.
     * @param value value to bind as bind_status
     */
    public void setbind_status(String value) {
        ensureVariableManager().setVariableValue("bind_status", value);
    }

    /**
     * Returns the variable value for bind_UserCenter.
     * @return variable value for bind_UserCenter
     */
    public String getbind_UserCenter() {
        return (String)ensureVariableManager().getVariableValue("bind_UserCenter");
    }

    /**
     * Sets <code>value</code> for variable bind_UserCenter.
     * @param value value to bind as bind_UserCenter
     */
    public void setbind_UserCenter(String value) {
        ensureVariableManager().setVariableValue("bind_UserCenter", value);
        executeQuery();
    }
    
    public void applyCenterCriteria(String center){
            setbind_UserCenter(center);
            setApplyViewCriteriaName("byUserCenterCriteria");
    }
}
