package com.fda.aps.model.viewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 15 04:12:59 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CenterItemNoROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CenterItemNoROVOImpl() {
    }

    @Override
    protected void create() {
        super.create();
        setManageRowsByKey(true);
    }
}
