package com.fda.aps.model.viewobject;

import com.fda.aps.model.entity.AapDetailedExpensesImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 02 14:49:00 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailedExpensesViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Allowance {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getAllowance();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAllowance((String)value);
            }
        }
        ,
        CenterItmNo {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getCenterItmNo();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setCenterItmNo((String)value);
            }
        }
        ,
        Cost {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getCost();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setCost((Number)value);
            }
        }
        ,
        CostCenter {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getCostCenter();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setCostCenter((String)value);
            }
        }
        ,
        ExpensesId {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getExpensesId();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setExpensesId((Number)value);
            }
        }
        ,
        Fund {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFund();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setFund((String)value);
            }
        }
        ,
        FundingObjCode {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFundingObjCode();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setFundingObjCode((String)value);
            }
        }
        ,
        RequestId {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getRequestId();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setRequestId((Number)value);
            }
        }
        ,
        SubAllowance {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getSubAllowance();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setSubAllowance((String)value);
            }
        }
        ,
        TotalCost {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getTotalCost();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setTotalCost((Number)value);
            }
        }
        ,
        TotAmtRem {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getTotAmtRem();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setTotAmtRem((Number)value);
            }
        }
        ,
        Bap {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getBap();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setBap((String)value);
            }
        }
        ,
        FiscalYear {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFiscalYear();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setFiscalYear((String)value);
            }
        }
        ,
        SubAllowanceDescrptn {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getSubAllowanceDescrptn();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setSubAllowanceDescrptn((String)value);
            }
        }
        ,
        FundingObjDescrptn {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFundingObjDescrptn();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setFundingObjDescrptn((String)value);
            }
        }
        ,
        CostCenterDescrptn {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getCostCenterDescrptn();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setCostCenterDescrptn((String)value);
            }
        }
        ,
        AllowanceDescrptn {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getAllowanceDescrptn();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAllowanceDescrptn((String)value);
            }
        }
        ,
        Center {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getCenter();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setCenter((String)value);
            }
        }
        ,
        FundDescrptn {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFundDescrptn();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setFundDescrptn((String)value);
            }
        }
        ,
        BapDescrptn {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getBapDescrptn();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setBapDescrptn((String)value);
            }
        }
        ,
        RequestsView {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getRequestsView();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SecurityGroupsMappingROView {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getSecurityGroupsMappingROView();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BapROView {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getBapROView();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FiscalYearROView {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFiscalYearROView();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FuncdingObjectClassROView {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFuncdingObjectClassROView();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FundROView {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getFundROView();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AapFundingObjectView {
            public Object get(DetailedExpensesViewRowImpl obj) {
                return obj.getAapFundingObjectView();
            }

            public void put(DetailedExpensesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DetailedExpensesViewRowImpl object);

        public abstract void put(DetailedExpensesViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ALLOWANCE = AttributesEnum.Allowance.index();
    public static final int CENTERITMNO = AttributesEnum.CenterItmNo.index();
    public static final int COST = AttributesEnum.Cost.index();
    public static final int COSTCENTER = AttributesEnum.CostCenter.index();
    public static final int EXPENSESID = AttributesEnum.ExpensesId.index();
    public static final int FUND = AttributesEnum.Fund.index();
    public static final int FUNDINGOBJCODE = AttributesEnum.FundingObjCode.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int SUBALLOWANCE = AttributesEnum.SubAllowance.index();
    public static final int TOTALCOST = AttributesEnum.TotalCost.index();
    public static final int TOTAMTREM = AttributesEnum.TotAmtRem.index();
    public static final int BAP = AttributesEnum.Bap.index();
    public static final int FISCALYEAR = AttributesEnum.FiscalYear.index();
    public static final int SUBALLOWANCEDESCRPTN = AttributesEnum.SubAllowanceDescrptn.index();
    public static final int FUNDINGOBJDESCRPTN = AttributesEnum.FundingObjDescrptn.index();
    public static final int COSTCENTERDESCRPTN = AttributesEnum.CostCenterDescrptn.index();
    public static final int ALLOWANCEDESCRPTN = AttributesEnum.AllowanceDescrptn.index();
    public static final int CENTER = AttributesEnum.Center.index();
    public static final int FUNDDESCRPTN = AttributesEnum.FundDescrptn.index();
    public static final int BAPDESCRPTN = AttributesEnum.BapDescrptn.index();
    public static final int REQUESTSVIEW = AttributesEnum.RequestsView.index();
    public static final int SECURITYGROUPSMAPPINGROVIEW = AttributesEnum.SecurityGroupsMappingROView.index();
    public static final int BAPROVIEW = AttributesEnum.BapROView.index();
    public static final int FISCALYEARROVIEW = AttributesEnum.FiscalYearROView.index();
    public static final int FUNCDINGOBJECTCLASSROVIEW = AttributesEnum.FuncdingObjectClassROView.index();
    public static final int FUNDROVIEW = AttributesEnum.FundROView.index();
    public static final int AAPFUNDINGOBJECTVIEW = AttributesEnum.AapFundingObjectView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DetailedExpensesViewRowImpl() {
    }

    /**
     * Gets AapDetailedExpenses entity object.
     * @return the AapDetailedExpenses
     */
    public AapDetailedExpensesImpl getAapDetailedExpenses() {
        return (AapDetailedExpensesImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ALLOWANCE using the alias name Allowance.
     * @return the ALLOWANCE
     */
    public String getAllowance() {
        return (String) getAttributeInternal(ALLOWANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWANCE using the alias name Allowance.
     * @param value value to set the ALLOWANCE
     */
    public void setAllowance(String value) {
        setAttributeInternal(ALLOWANCE, value);
    }

    /**
     * Gets the attribute value for CENTER_ITM_NO using the alias name CenterItmNo.
     * @return the CENTER_ITM_NO
     */
    public String getCenterItmNo() {
        return (String) getAttributeInternal(CENTERITMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CENTER_ITM_NO using the alias name CenterItmNo.
     * @param value value to set the CENTER_ITM_NO
     */
    public void setCenterItmNo(String value) {
        setAttributeInternal(CENTERITMNO, value);
    }

    /**
     * Gets the attribute value for COST using the alias name Cost.
     * @return the COST
     */
    public Number getCost() {
        return (Number) getAttributeInternal(COST);
    }

    /**
     * Sets <code>value</code> as attribute value for COST using the alias name Cost.
     * @param value value to set the COST
     */
    public void setCost(Number value) {
        setAttributeInternal(COST, value);
    }

    /**
     * Gets the attribute value for COST_CENTER using the alias name CostCenter.
     * @return the COST_CENTER
     */
    public String getCostCenter() {
        return (String) getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CENTER using the alias name CostCenter.
     * @param value value to set the COST_CENTER
     */
    public void setCostCenter(String value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for EXPENSES_ID using the alias name ExpensesId.
     * @return the EXPENSES_ID
     */
    public Number getExpensesId() {
        return (Number) getAttributeInternal(EXPENSESID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENSES_ID using the alias name ExpensesId.
     * @param value value to set the EXPENSES_ID
     */
    public void setExpensesId(Number value) {
        setAttributeInternal(EXPENSESID, value);
    }

    /**
     * Gets the attribute value for FUND using the alias name Fund.
     * @return the FUND
     */
    public String getFund() {
        return (String) getAttributeInternal(FUND);
    }

    /**
     * Sets <code>value</code> as attribute value for FUND using the alias name Fund.
     * @param value value to set the FUND
     */
    public void setFund(String value) {
        setAttributeInternal(FUND, value);
    }

    /**
     * Gets the attribute value for FUNDING_OBJ_CODE using the alias name FundingObjCode.
     * @return the FUNDING_OBJ_CODE
     */
    public String getFundingObjCode() {
        return (String) getAttributeInternal(FUNDINGOBJCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNDING_OBJ_CODE using the alias name FundingObjCode.
     * @param value value to set the FUNDING_OBJ_CODE
     */
    public void setFundingObjCode(String value) {
        setAttributeInternal(FUNDINGOBJCODE, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for SUB_ALLOWANCE using the alias name SubAllowance.
     * @return the SUB_ALLOWANCE
     */
    public String getSubAllowance() {
        return (String) getAttributeInternal(SUBALLOWANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_ALLOWANCE using the alias name SubAllowance.
     * @param value value to set the SUB_ALLOWANCE
     */
    public void setSubAllowance(String value) {
        setAttributeInternal(SUBALLOWANCE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalCost.
     * @return the TotalCost
     */
    public Number getTotalCost() {
        return (Number) getAttributeInternal(TOTALCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalCost.
     * @param value value to set the  TotalCost
     */
    public void setTotalCost(Number value) {
        setAttributeInternal(TOTALCOST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotAmtRem.
     * @return the TotAmtRem
     */
    public Number getTotAmtRem() {
        return (Number) getAttributeInternal(TOTAMTREM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotAmtRem.
     * @param value value to set the  TotAmtRem
     */
    public void setTotAmtRem(Number value) {
        setAttributeInternal(TOTAMTREM, value);
    }

    /**
     * Gets the attribute value for BAP using the alias name Bap.
     * @return the BAP
     */
    public String getBap() {
        return (String) getAttributeInternal(BAP);
    }

    /**
     * Sets <code>value</code> as attribute value for BAP using the alias name Bap.
     * @param value value to set the BAP
     */
    public void setBap(String value) {
        setAttributeInternal(BAP, value);
    }

    /**
     * Gets the attribute value for FISCAL_YEAR using the alias name FiscalYear.
     * @return the FISCAL_YEAR
     */
    public String getFiscalYear() {
        return (String) getAttributeInternal(FISCALYEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for FISCAL_YEAR using the alias name FiscalYear.
     * @param value value to set the FISCAL_YEAR
     */
    public void setFiscalYear(String value) {
        setAttributeInternal(FISCALYEAR, value);
    }

    /**
     * Gets the attribute value for SUB_ALLOWANCE_DESCRPTN using the alias name SubAllowanceDescrptn.
     * @return the SUB_ALLOWANCE_DESCRPTN
     */
    public String getSubAllowanceDescrptn() {
        return (String) getAttributeInternal(SUBALLOWANCEDESCRPTN);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_ALLOWANCE_DESCRPTN using the alias name SubAllowanceDescrptn.
     * @param value value to set the SUB_ALLOWANCE_DESCRPTN
     */
    public void setSubAllowanceDescrptn(String value) {
        setAttributeInternal(SUBALLOWANCEDESCRPTN, value);
    }

    /**
     * Gets the attribute value for FUNDING_OBJ_DESCRPTN using the alias name FundingObjDescrptn.
     * @return the FUNDING_OBJ_DESCRPTN
     */
    public String getFundingObjDescrptn() {
        return (String) getAttributeInternal(FUNDINGOBJDESCRPTN);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNDING_OBJ_DESCRPTN using the alias name FundingObjDescrptn.
     * @param value value to set the FUNDING_OBJ_DESCRPTN
     */
    public void setFundingObjDescrptn(String value) {
        setAttributeInternal(FUNDINGOBJDESCRPTN, value);
    }

    /**
     * Gets the attribute value for COST_CENTER_DESCRPTN using the alias name CostCenterDescrptn.
     * @return the COST_CENTER_DESCRPTN
     */
    public String getCostCenterDescrptn() {
        return (String) getAttributeInternal(COSTCENTERDESCRPTN);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CENTER_DESCRPTN using the alias name CostCenterDescrptn.
     * @param value value to set the COST_CENTER_DESCRPTN
     */
    public void setCostCenterDescrptn(String value) {
        setAttributeInternal(COSTCENTERDESCRPTN, value);
    }

    /**
     * Gets the attribute value for ALLOWANCE_DESCRPTN using the alias name AllowanceDescrptn.
     * @return the ALLOWANCE_DESCRPTN
     */
    public String getAllowanceDescrptn() {
        return (String) getAttributeInternal(ALLOWANCEDESCRPTN);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWANCE_DESCRPTN using the alias name AllowanceDescrptn.
     * @param value value to set the ALLOWANCE_DESCRPTN
     */
    public void setAllowanceDescrptn(String value) {
        setAttributeInternal(ALLOWANCEDESCRPTN, value);
    }

    /**
     * Gets the attribute value for CENTER using the alias name Center.
     * @return the CENTER
     */
    public String getCenter() {
        return (String) getAttributeInternal(CENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for CENTER using the alias name Center.
     * @param value value to set the CENTER
     */
    public void setCenter(String value) {
        setAttributeInternal(CENTER, value);
    }

    /**
     * Gets the attribute value for FUND_DESCRPTN using the alias name FundDescrptn.
     * @return the FUND_DESCRPTN
     */
    public String getFundDescrptn() {
        return (String) getAttributeInternal(FUNDDESCRPTN);
    }

    /**
     * Sets <code>value</code> as attribute value for FUND_DESCRPTN using the alias name FundDescrptn.
     * @param value value to set the FUND_DESCRPTN
     */
    public void setFundDescrptn(String value) {
        setAttributeInternal(FUNDDESCRPTN, value);
    }

    /**
     * Gets the attribute value for BAP_DESCRPTN using the alias name BapDescrptn.
     * @return the BAP_DESCRPTN
     */
    public String getBapDescrptn() {
        return (String) getAttributeInternal(BAPDESCRPTN);
    }

    /**
     * Sets <code>value</code> as attribute value for BAP_DESCRPTN using the alias name BapDescrptn.
     * @param value value to set the BAP_DESCRPTN
     */
    public void setBapDescrptn(String value) {
        setAttributeInternal(BAPDESCRPTN, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RequestsView.
     */
    public RowSet getRequestsView() {
        return (RowSet)getAttributeInternal(REQUESTSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SecurityGroupsMappingROView.
     */
    public RowSet getSecurityGroupsMappingROView() {
        return (RowSet)getAttributeInternal(SECURITYGROUPSMAPPINGROVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BapROView.
     */
    public RowSet getBapROView() {
        return (RowSet)getAttributeInternal(BAPROVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FiscalYearROView.
     */
    public RowSet getFiscalYearROView() {
        return (RowSet)getAttributeInternal(FISCALYEARROVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FuncdingObjectClassROView.
     */
    public RowSet getFuncdingObjectClassROView() {
        return (RowSet)getAttributeInternal(FUNCDINGOBJECTCLASSROVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FundROView.
     */
    public RowSet getFundROView() {
        return (RowSet)getAttributeInternal(FUNDROVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AapFundingObjectView.
     */
    public RowSet getAapFundingObjectView() {
        return (RowSet)getAttributeInternal(AAPFUNDINGOBJECTVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
