package com.fda.aps.model.viewobject;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 11 15:24:05 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RequestsViewImpl() {
    }

    /**
     * Returns the variable value for bind_submitFlag.
     * @return variable value for bind_submitFlag
     */
    public String getbind_submitFlag() {
        return (String)ensureVariableManager().getVariableValue("bind_submitFlag");
    }

    /**
     * Sets <code>value</code> for variable bind_submitFlag.
     * @param value value to bind as bind_submitFlag
     */
    public void setbind_submitFlag(String value) {
        ensureVariableManager().setVariableValue("bind_submitFlag", value);
    }

    /**
     * Returns the variable value for bind_RequestId.
     * @return variable value for bind_RequestId
     */
    public String getbind_RequestId() {
        return (String)ensureVariableManager().getVariableValue("bind_RequestId");
    }

    /**
     * Sets <code>value</code> for variable bind_RequestId.
     * @param value value to bind as bind_RequestId
     */
    public void setbind_RequestId(String value) {
        ensureVariableManager().setVariableValue("bind_RequestId", value);
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    /**
     * Returns the variable value for bind_Center.
     * @return variable value for bind_Center
     */
    public String getbind_Center() {
        return (String)ensureVariableManager().getVariableValue("bind_Center");
    }

    /**
     * Sets <code>value</code> for variable bind_Center.
     * @param value value to bind as bind_Center
     */
    public void setbind_Center(String value) {
        ensureVariableManager().setVariableValue("bind_Center", value);
    }
}
