package com.fda.aps.model.viewobject.client;

import com.fda.aps.model.viewobject.common.AapFundingObjectView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 03:04:39 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AapFundingObjectViewClient extends ViewUsageImpl implements AapFundingObjectView {
    /**
     * This is the default constructor (do not remove).
     */
    public AapFundingObjectViewClient() {
    }

    public void setbind_Type(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setbind_Type",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
