package com.fda.aps.model.viewobject.client;

import com.fda.aps.model.viewobject.common.APSSearchView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 30 22:16:25 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class APSSearchViewClient extends ViewUsageImpl implements APSSearchView {
    /**
     * This is the default constructor (do not remove).
     */
    public APSSearchViewClient() {
    }

    public void setbind_UserCenter(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setbind_UserCenter",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
