package com.fda.aps.model.viewobject;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 25 18:06:14 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AapSlaCutoffdateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AapSlaCutoffdateVOImpl() {
    }

    @Override
    public void insertRow(Row row) {
        super.insertRow(row);
        row.removeAndRetain();
        last();
        next();
        getDefaultRowSet().insertRow(row);
    }
} 

