package com.fda.aps.model.viewobject;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;

import utils.system;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 29 22:49:03 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApsReferenceViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApsReferenceViewImpl() {
    }

    /**
     * Returns the bind variable value for bind_RefType.
     * @return bind variable value for bind_RefType
     */
    public String getbind_RefType() {
        return (String)getNamedWhereClauseParam("bind_RefType");
    }

    /**
     * Sets <code>value</code> for bind variable bind_RefType.
     * @param value value to bind as bind_RefType
     */
    public void setbind_RefType(String value) {
        setNamedWhereClauseParam("bind_RefType", value);
    }

    @Override
    protected void create() {
        System.out.println("test");
        super.create();
    }

    /**
     * Returns the variable value for bind_effDate.
     * @return variable value for bind_effDate
     */
    public Date getbind_effDate() {
        return (Date)ensureVariableManager().getVariableValue("bind_effDate");
    }

    /**
     * Sets <code>value</code> for variable bind_effDate.
     * @param value value to bind as bind_effDate
     */
    public void setbind_effDate(Date value) {
        ensureVariableManager().setVariableValue("bind_effDate", value);
    }

    /**
     * Returns the variable value for bind_RefId.
     * @return variable value for bind_RefId
     */
    public String getbind_RefId() {
        return (String)ensureVariableManager().getVariableValue("bind_RefId");
    }

    /**
     * Sets <code>value</code> for variable bind_RefId.
     * @param value value to bind as bind_RefId
     */
    public void setbind_RefId(String value) {
        ensureVariableManager().setVariableValue("bind_RefId", value);
    }
}
