package com.fda.aps.model.viewobject;

import com.fda.aps.model.entity.AapRequestsImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 11 15:24:34 EDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestsViewRowImpl extends ViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RequestSequence,
        AcquisitionStatus,
        AnticipatedAcquisitionMethod,
        AnticipatedActionType,
        AnticipatedNoOfAwards,
        AnticipatedPop,
        CenterId,
        CollaborationFlag,
        CollaborationItemNo,
        CommodityType,
        CreatedBy,
        CreatedDate,
        CtrLnItmNo,
        CurrYrPopEndDate,
        DetailedDescription,
        EstimatedNumberOfActions,
        EstimatedRfaRelDate,
        EstimatedTotalProjValue,
        ExistingDocNo,
        ExistingIaaNumber,
        FiscalYear,
        GrantsCommodity,
        LastUpdatedBy,
        LastUpdatedDate,
        LeadMngCenter,
        NaicsCode,
        NciboardReviewRequired,
        OptionYrExercise,
        OwnerNmTelNo,
        PotentialContractType,
        PriorityLevel,
        ProductServiceCode,
        ProjectPopEndDate,
        ProjectPopStartDate,
        Purpose,
        RecurringItem,
        ReimbursableAgency,
        ReimbursableAmt,
        ReleaseNumber,
        RequestId,
        RequiredAwardDate,
        RequirementType,
        RequisitionNo,
        ServiceOrReimbursable,
        SubmitFlag,
        TotalDlarsForCurtFy,
        ZeroDollarReqn,
        TotalAmountRemaining,
        TransProjectValueCode,
        Branch,
        Division,
        DueDate,
        TransSLANumdays,
        TransReqType,
        SubOfc,
        SuperOfc,
        TransSupOfcCode,
        TotalDlarsCrntYr,
        RequestTitle,
        PointOfContactView,
        AapNotificationView,
        DetailedExpensesView,
        AapCollaborationView,
        AapCommentsVO,
        NAICSReferenceView,
        LeadManagingCenterLOV,
        ProrityLevelLOV,
        ServiceOrReimbursableLOV,
        SORList,
        CollaborationItemLOV,
        AcqisitionStatusLOV,
        OptionYearLOV,
        AnticipatedActionTypeLOV,
        PotentialContractTypeLOV,
        RequirementTypeLOV,
        CommodityTypeLOV,
        ProductServiceCodeLOV,
        CompetitionTypeLOV,
        EstimatedTotalProjectValueLOV,
        GrantsCommodityLOV,
        YesNoView,
        FiscalYearLOV,
        DetailedExpensesVO,
        SubOfficeLOV,
        SupOfficeLOV,
        CurrentYearProjectValueLOV,
        EstimatedValueRangeVO,
        EstimatedProjectValueRangeLOV;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int REQUESTSEQUENCE = AttributesEnum.RequestSequence.index();
    public static final int ACQUISITIONSTATUS = AttributesEnum.AcquisitionStatus.index();
    public static final int ANTICIPATEDACQUISITIONMETHOD = AttributesEnum.AnticipatedAcquisitionMethod.index();
    public static final int ANTICIPATEDACTIONTYPE = AttributesEnum.AnticipatedActionType.index();
    public static final int ANTICIPATEDNOOFAWARDS = AttributesEnum.AnticipatedNoOfAwards.index();
    public static final int ANTICIPATEDPOP = AttributesEnum.AnticipatedPop.index();
    public static final int CENTERID = AttributesEnum.CenterId.index();
    public static final int COLLABORATIONFLAG = AttributesEnum.CollaborationFlag.index();
    public static final int COLLABORATIONITEMNO = AttributesEnum.CollaborationItemNo.index();
    public static final int COMMODITYTYPE = AttributesEnum.CommodityType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CTRLNITMNO = AttributesEnum.CtrLnItmNo.index();
    public static final int CURRYRPOPENDDATE = AttributesEnum.CurrYrPopEndDate.index();
    public static final int DETAILEDDESCRIPTION = AttributesEnum.DetailedDescription.index();
    public static final int ESTIMATEDNUMBEROFACTIONS = AttributesEnum.EstimatedNumberOfActions.index();
    public static final int ESTIMATEDRFARELDATE = AttributesEnum.EstimatedRfaRelDate.index();
    public static final int ESTIMATEDTOTALPROJVALUE = AttributesEnum.EstimatedTotalProjValue.index();
    public static final int EXISTINGDOCNO = AttributesEnum.ExistingDocNo.index();
    public static final int EXISTINGIAANUMBER = AttributesEnum.ExistingIaaNumber.index();
    public static final int FISCALYEAR = AttributesEnum.FiscalYear.index();
    public static final int GRANTSCOMMODITY = AttributesEnum.GrantsCommodity.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LEADMNGCENTER = AttributesEnum.LeadMngCenter.index();
    public static final int NAICSCODE = AttributesEnum.NaicsCode.index();
    public static final int NCIBOARDREVIEWREQUIRED = AttributesEnum.NciboardReviewRequired.index();
    public static final int OPTIONYREXERCISE = AttributesEnum.OptionYrExercise.index();
    public static final int OWNERNMTELNO = AttributesEnum.OwnerNmTelNo.index();
    public static final int POTENTIALCONTRACTTYPE = AttributesEnum.PotentialContractType.index();
    public static final int PRIORITYLEVEL = AttributesEnum.PriorityLevel.index();
    public static final int PRODUCTSERVICECODE = AttributesEnum.ProductServiceCode.index();
    public static final int PROJECTPOPENDDATE = AttributesEnum.ProjectPopEndDate.index();
    public static final int PROJECTPOPSTARTDATE = AttributesEnum.ProjectPopStartDate.index();
    public static final int PURPOSE = AttributesEnum.Purpose.index();
    public static final int RECURRINGITEM = AttributesEnum.RecurringItem.index();
    public static final int REIMBURSABLEAGENCY = AttributesEnum.ReimbursableAgency.index();
    public static final int REIMBURSABLEAMT = AttributesEnum.ReimbursableAmt.index();
    public static final int RELEASENUMBER = AttributesEnum.ReleaseNumber.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int REQUIREDAWARDDATE = AttributesEnum.RequiredAwardDate.index();
    public static final int REQUIREMENTTYPE = AttributesEnum.RequirementType.index();
    public static final int REQUISITIONNO = AttributesEnum.RequisitionNo.index();
    public static final int SERVICEORREIMBURSABLE = AttributesEnum.ServiceOrReimbursable.index();
    public static final int SUBMITFLAG = AttributesEnum.SubmitFlag.index();
    public static final int TOTALDLARSFORCURTFY = AttributesEnum.TotalDlarsForCurtFy.index();
    public static final int ZERODOLLARREQN = AttributesEnum.ZeroDollarReqn.index();
    public static final int TOTALAMOUNTREMAINING = AttributesEnum.TotalAmountRemaining.index();
    public static final int TRANSPROJECTVALUECODE = AttributesEnum.TransProjectValueCode.index();
    public static final int BRANCH = AttributesEnum.Branch.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int TRANSSLANUMDAYS = AttributesEnum.TransSLANumdays.index();
    public static final int TRANSREQTYPE = AttributesEnum.TransReqType.index();
    public static final int SUBOFC = AttributesEnum.SubOfc.index();
    public static final int SUPEROFC = AttributesEnum.SuperOfc.index();
    public static final int TRANSSUPOFCCODE = AttributesEnum.TransSupOfcCode.index();
    public static final int TOTALDLARSCRNTYR = AttributesEnum.TotalDlarsCrntYr.index();
    public static final int REQUESTTITLE = AttributesEnum.RequestTitle.index();
    public static final int POINTOFCONTACTVIEW = AttributesEnum.PointOfContactView.index();
    public static final int AAPNOTIFICATIONVIEW = AttributesEnum.AapNotificationView.index();
    public static final int DETAILEDEXPENSESVIEW = AttributesEnum.DetailedExpensesView.index();
    public static final int AAPCOLLABORATIONVIEW = AttributesEnum.AapCollaborationView.index();
    public static final int AAPCOMMENTSVO = AttributesEnum.AapCommentsVO.index();
    public static final int NAICSREFERENCEVIEW = AttributesEnum.NAICSReferenceView.index();
    public static final int LEADMANAGINGCENTERLOV = AttributesEnum.LeadManagingCenterLOV.index();
    public static final int PRORITYLEVELLOV = AttributesEnum.ProrityLevelLOV.index();
    public static final int SERVICEORREIMBURSABLELOV = AttributesEnum.ServiceOrReimbursableLOV.index();
    public static final int SORLIST = AttributesEnum.SORList.index();
    public static final int COLLABORATIONITEMLOV = AttributesEnum.CollaborationItemLOV.index();
    public static final int ACQISITIONSTATUSLOV = AttributesEnum.AcqisitionStatusLOV.index();
    public static final int OPTIONYEARLOV = AttributesEnum.OptionYearLOV.index();
    public static final int ANTICIPATEDACTIONTYPELOV = AttributesEnum.AnticipatedActionTypeLOV.index();
    public static final int POTENTIALCONTRACTTYPELOV = AttributesEnum.PotentialContractTypeLOV.index();
    public static final int REQUIREMENTTYPELOV = AttributesEnum.RequirementTypeLOV.index();
    public static final int COMMODITYTYPELOV = AttributesEnum.CommodityTypeLOV.index();
    public static final int PRODUCTSERVICECODELOV = AttributesEnum.ProductServiceCodeLOV.index();
    public static final int COMPETITIONTYPELOV = AttributesEnum.CompetitionTypeLOV.index();
    public static final int ESTIMATEDTOTALPROJECTVALUELOV = AttributesEnum.EstimatedTotalProjectValueLOV.index();
    public static final int GRANTSCOMMODITYLOV = AttributesEnum.GrantsCommodityLOV.index();
    public static final int YESNOVIEW = AttributesEnum.YesNoView.index();
    public static final int FISCALYEARLOV = AttributesEnum.FiscalYearLOV.index();
    public static final int DETAILEDEXPENSESVO = AttributesEnum.DetailedExpensesVO.index();
    public static final int SUBOFFICELOV = AttributesEnum.SubOfficeLOV.index();
    public static final int SUPOFFICELOV = AttributesEnum.SupOfficeLOV.index();
    public static final int CURRENTYEARPROJECTVALUELOV = AttributesEnum.CurrentYearProjectValueLOV.index();
    public static final int ESTIMATEDVALUERANGEVO = AttributesEnum.EstimatedValueRangeVO.index();
    public static final int ESTIMATEDPROJECTVALUERANGELOV = AttributesEnum.EstimatedProjectValueRangeLOV.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RequestsViewRowImpl() {
    }

    /**
     * Gets AapRequests entity object.
     * @return the AapRequests
     */
    public AapRequestsImpl getAapRequests() {
        return (AapRequestsImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for the calculated attribute RequestSequence.
     * @return the RequestSequence
     */
    public String getRequestSequence() {
        return (String) getAttributeInternal(REQUESTSEQUENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequestSequence.
     * @param value value to set the  RequestSequence
     */
    public void setRequestSequence(String value) {
        setAttributeInternal(REQUESTSEQUENCE, value);
    }

    /**
     * Gets the attribute value for ACQUISITION_STATUS using the alias name AcquisitionStatus.
     * @return the ACQUISITION_STATUS
     */
    public Number getAcquisitionStatus() {
        return (Number) getAttributeInternal(ACQUISITIONSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for ACQUISITION_STATUS using the alias name AcquisitionStatus.
     * @param value value to set the ACQUISITION_STATUS
     */
    public void setAcquisitionStatus(Number value) {
        setAttributeInternal(ACQUISITIONSTATUS, value);
    }

    /**
     * Gets the attribute value for ANTICIPATED_ACQUISITION_METHOD using the alias name AnticipatedAcquisitionMethod.
     * @return the ANTICIPATED_ACQUISITION_METHOD
     */
    public Number getAnticipatedAcquisitionMethod() {
        return (Number) getAttributeInternal(ANTICIPATEDACQUISITIONMETHOD);
    }

    /**
     * Sets <code>value</code> as attribute value for ANTICIPATED_ACQUISITION_METHOD using the alias name AnticipatedAcquisitionMethod.
     * @param value value to set the ANTICIPATED_ACQUISITION_METHOD
     */
    public void setAnticipatedAcquisitionMethod(Number value) {
        setAttributeInternal(ANTICIPATEDACQUISITIONMETHOD, value);
    }

    /**
     * Gets the attribute value for ANTICIPATED_ACTION_TYPE using the alias name AnticipatedActionType.
     * @return the ANTICIPATED_ACTION_TYPE
     */
    public Number getAnticipatedActionType() {
        return (Number) getAttributeInternal(ANTICIPATEDACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ANTICIPATED_ACTION_TYPE using the alias name AnticipatedActionType.
     * @param value value to set the ANTICIPATED_ACTION_TYPE
     */
    public void setAnticipatedActionType(Number value) {
        setAttributeInternal(ANTICIPATEDACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for ANTICIPATED_NO_OF_AWARDS using the alias name AnticipatedNoOfAwards.
     * @return the ANTICIPATED_NO_OF_AWARDS
     */
    public String getAnticipatedNoOfAwards() {
        return (String) getAttributeInternal(ANTICIPATEDNOOFAWARDS);
    }

    /**
     * Sets <code>value</code> as attribute value for ANTICIPATED_NO_OF_AWARDS using the alias name AnticipatedNoOfAwards.
     * @param value value to set the ANTICIPATED_NO_OF_AWARDS
     */
    public void setAnticipatedNoOfAwards(String value) {
        setAttributeInternal(ANTICIPATEDNOOFAWARDS, value);
    }

    /**
     * Gets the attribute value for ANTICIPATED_POP using the alias name AnticipatedPop.
     * @return the ANTICIPATED_POP
     */
    public String getAnticipatedPop() {
        return (String) getAttributeInternal(ANTICIPATEDPOP);
    }

    /**
     * Sets <code>value</code> as attribute value for ANTICIPATED_POP using the alias name AnticipatedPop.
     * @param value value to set the ANTICIPATED_POP
     */
    public void setAnticipatedPop(String value) {
        setAttributeInternal(ANTICIPATEDPOP, value);
    }

    /**
     * Gets the attribute value for CENTER_ID using the alias name CenterId.
     * @return the CENTER_ID
     */
    public String getCenterId() {
        return (String) getAttributeInternal(CENTERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CENTER_ID using the alias name CenterId.
     * @param value value to set the CENTER_ID
     */
    public void setCenterId(String value) {
        setAttributeInternal(CENTERID, value);
    }

    /**
     * Gets the attribute value for COLLABORATION_FLAG using the alias name CollaborationFlag.
     * @return the COLLABORATION_FLAG
     */
    public String getCollaborationFlag() {
        return (String) getAttributeInternal(COLLABORATIONFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for COLLABORATION_FLAG using the alias name CollaborationFlag.
     * @param value value to set the COLLABORATION_FLAG
     */
    public void setCollaborationFlag(String value) {
        setAttributeInternal(COLLABORATIONFLAG, value);
    }

    /**
     * Gets the attribute value for COLLABORATION_ITEM_NO using the alias name CollaborationItemNo.
     * @return the COLLABORATION_ITEM_NO
     */
    public String getCollaborationItemNo() {
        return (String) getAttributeInternal(COLLABORATIONITEMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COLLABORATION_ITEM_NO using the alias name CollaborationItemNo.
     * @param value value to set the COLLABORATION_ITEM_NO
     */
    public void setCollaborationItemNo(String value) {
        setAttributeInternal(COLLABORATIONITEMNO, value);
    }

    /**
     * Gets the attribute value for COMMODITY_TYPE using the alias name CommodityType.
     * @return the COMMODITY_TYPE
     */
    public Number getCommodityType() {
        return (Number) getAttributeInternal(COMMODITYTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMODITY_TYPE using the alias name CommodityType.
     * @param value value to set the COMMODITY_TYPE
     */
    public void setCommodityType(Number value) {
        setAttributeInternal(COMMODITYTYPE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CTR_LN_ITM_NO using the alias name CtrLnItmNo.
     * @return the CTR_LN_ITM_NO
     */
    public String getCtrLnItmNo() {
        return (String) getAttributeInternal(CTRLNITMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CTR_LN_ITM_NO using the alias name CtrLnItmNo.
     * @param value value to set the CTR_LN_ITM_NO
     */
    public void setCtrLnItmNo(String value) {
        setAttributeInternal(CTRLNITMNO, value);
    }

    /**
     * Gets the attribute value for CURR_YR_POP_END_DATE using the alias name CurrYrPopEndDate.
     * @return the CURR_YR_POP_END_DATE
     */
    public Date getCurrYrPopEndDate() {
        return (Date) getAttributeInternal(CURRYRPOPENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURR_YR_POP_END_DATE using the alias name CurrYrPopEndDate.
     * @param value value to set the CURR_YR_POP_END_DATE
     */
    public void setCurrYrPopEndDate(Date value) {
        setAttributeInternal(CURRYRPOPENDDATE, value);
    }

    /**
     * Gets the attribute value for DETAILED_DESCRIPTION using the alias name DetailedDescription.
     * @return the DETAILED_DESCRIPTION
     */
    public String getDetailedDescription() {
        return (String) getAttributeInternal(DETAILEDDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAILED_DESCRIPTION using the alias name DetailedDescription.
     * @param value value to set the DETAILED_DESCRIPTION
     */
    public void setDetailedDescription(String value) {
        setAttributeInternal(DETAILEDDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ESTIMATED_NUMBER_OF_ACTIONS using the alias name EstimatedNumberOfActions.
     * @return the ESTIMATED_NUMBER_OF_ACTIONS
     */
    public String getEstimatedNumberOfActions() {
        return (String) getAttributeInternal(ESTIMATEDNUMBEROFACTIONS);
    }

    /**
     * Sets <code>value</code> as attribute value for ESTIMATED_NUMBER_OF_ACTIONS using the alias name EstimatedNumberOfActions.
     * @param value value to set the ESTIMATED_NUMBER_OF_ACTIONS
     */
    public void setEstimatedNumberOfActions(String value) {
        setAttributeInternal(ESTIMATEDNUMBEROFACTIONS, value);
    }

    /**
     * Gets the attribute value for ESTIMATED_RFA_REL_DATE using the alias name EstimatedRfaRelDate.
     * @return the ESTIMATED_RFA_REL_DATE
     */
    public Date getEstimatedRfaRelDate() {
        return (Date) getAttributeInternal(ESTIMATEDRFARELDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ESTIMATED_RFA_REL_DATE using the alias name EstimatedRfaRelDate.
     * @param value value to set the ESTIMATED_RFA_REL_DATE
     */
    public void setEstimatedRfaRelDate(Date value) {
        setAttributeInternal(ESTIMATEDRFARELDATE, value);
    }

    /**
     * Gets the attribute value for ESTIMATED_TOTAL_PROJ_VALUE using the alias name EstimatedTotalProjValue.
     * @return the ESTIMATED_TOTAL_PROJ_VALUE
     */
    public Number getEstimatedTotalProjValue() {
        return (Number) getAttributeInternal(ESTIMATEDTOTALPROJVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for ESTIMATED_TOTAL_PROJ_VALUE using the alias name EstimatedTotalProjValue.
     * @param value value to set the ESTIMATED_TOTAL_PROJ_VALUE
     */
    public void setEstimatedTotalProjValue(Number value) {
        setAttributeInternal(ESTIMATEDTOTALPROJVALUE, value);
    }

    /**
     * Gets the attribute value for EXISTING_DOC_NO using the alias name ExistingDocNo.
     * @return the EXISTING_DOC_NO
     */
    public String getExistingDocNo() {
        return (String) getAttributeInternal(EXISTINGDOCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for EXISTING_DOC_NO using the alias name ExistingDocNo.
     * @param value value to set the EXISTING_DOC_NO
     */
    public void setExistingDocNo(String value) {
        setAttributeInternal(EXISTINGDOCNO, value);
    }

    /**
     * Gets the attribute value for EXISTING_IAA_NUMBER using the alias name ExistingIaaNumber.
     * @return the EXISTING_IAA_NUMBER
     */
    public String getExistingIaaNumber() {
        return (String) getAttributeInternal(EXISTINGIAANUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for EXISTING_IAA_NUMBER using the alias name ExistingIaaNumber.
     * @param value value to set the EXISTING_IAA_NUMBER
     */
    public void setExistingIaaNumber(String value) {
        setAttributeInternal(EXISTINGIAANUMBER, value);
    }

    /**
     * Gets the attribute value for FISCAL_YEAR using the alias name FiscalYear.
     * @return the FISCAL_YEAR
     */
    public Number getFiscalYear() {
        return (Number) getAttributeInternal(FISCALYEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for FISCAL_YEAR using the alias name FiscalYear.
     * @param value value to set the FISCAL_YEAR
     */
    public void setFiscalYear(Number value) {
        setAttributeInternal(FISCALYEAR, value);
    }

    /**
     * Gets the attribute value for GRANTS_COMMODITY using the alias name GrantsCommodity.
     * @return the GRANTS_COMMODITY
     */
    public Number getGrantsCommodity() {
        return (Number) getAttributeInternal(GRANTSCOMMODITY);
    }

    /**
     * Sets <code>value</code> as attribute value for GRANTS_COMMODITY using the alias name GrantsCommodity.
     * @param value value to set the GRANTS_COMMODITY
     */
    public void setGrantsCommodity(Number value) {
        setAttributeInternal(GRANTSCOMMODITY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LEAD_MNG_CENTER using the alias name LeadMngCenter.
     * @return the LEAD_MNG_CENTER
     */
    public Number getLeadMngCenter() {
        return (Number) getAttributeInternal(LEADMNGCENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAD_MNG_CENTER using the alias name LeadMngCenter.
     * @param value value to set the LEAD_MNG_CENTER
     */
    public void setLeadMngCenter(Number value) {
        setAttributeInternal(LEADMNGCENTER, value);
    }

    /**
     * Gets the attribute value for NAICS_CODE using the alias name NaicsCode.
     * @return the NAICS_CODE
     */
    public Number getNaicsCode() {
        return (Number) getAttributeInternal(NAICSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for NAICS_CODE using the alias name NaicsCode.
     * @param value value to set the NAICS_CODE
     */
    public void setNaicsCode(Number value) {
        setAttributeInternal(NAICSCODE, value);
    }

    /**
     * Gets the attribute value for NCIBOARD_REVIEW_REQUIRED using the alias name NciboardReviewRequired.
     * @return the NCIBOARD_REVIEW_REQUIRED
     */
    public String getNciboardReviewRequired() {
        return (String) getAttributeInternal(NCIBOARDREVIEWREQUIRED);
    }

    /**
     * Sets <code>value</code> as attribute value for NCIBOARD_REVIEW_REQUIRED using the alias name NciboardReviewRequired.
     * @param value value to set the NCIBOARD_REVIEW_REQUIRED
     */
    public void setNciboardReviewRequired(String value) {
        setAttributeInternal(NCIBOARDREVIEWREQUIRED, value);
    }

    /**
     * Gets the attribute value for OPTION_YR_EXERCISE using the alias name OptionYrExercise.
     * @return the OPTION_YR_EXERCISE
     */
    public Number getOptionYrExercise() {
        return (Number) getAttributeInternal(OPTIONYREXERCISE);
    }

    /**
     * Sets <code>value</code> as attribute value for OPTION_YR_EXERCISE using the alias name OptionYrExercise.
     * @param value value to set the OPTION_YR_EXERCISE
     */
    public void setOptionYrExercise(Number value) {
        setAttributeInternal(OPTIONYREXERCISE, value);
    }

    /**
     * Gets the attribute value for OWNER_NM_TEL_NO using the alias name OwnerNmTelNo.
     * @return the OWNER_NM_TEL_NO
     */
    public String getOwnerNmTelNo() {
        return (String) getAttributeInternal(OWNERNMTELNO);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNER_NM_TEL_NO using the alias name OwnerNmTelNo.
     * @param value value to set the OWNER_NM_TEL_NO
     */
    public void setOwnerNmTelNo(String value) {
        setAttributeInternal(OWNERNMTELNO, value);
    }

    /**
     * Gets the attribute value for POTENTIAL_CONTRACT_TYPE using the alias name PotentialContractType.
     * @return the POTENTIAL_CONTRACT_TYPE
     */
    public Number getPotentialContractType() {
        return (Number) getAttributeInternal(POTENTIALCONTRACTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for POTENTIAL_CONTRACT_TYPE using the alias name PotentialContractType.
     * @param value value to set the POTENTIAL_CONTRACT_TYPE
     */
    public void setPotentialContractType(Number value) {
        setAttributeInternal(POTENTIALCONTRACTTYPE, value);
    }

    /**
     * Gets the attribute value for PRIORITY_LEVEL using the alias name PriorityLevel.
     * @return the PRIORITY_LEVEL
     */
    public Number getPriorityLevel() {
        return (Number) getAttributeInternal(PRIORITYLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY_LEVEL using the alias name PriorityLevel.
     * @param value value to set the PRIORITY_LEVEL
     */
    public void setPriorityLevel(Number value) {
        setAttributeInternal(PRIORITYLEVEL, value);
    }

    /**
     * Gets the attribute value for PRODUCT_SERVICE_CODE using the alias name ProductServiceCode.
     * @return the PRODUCT_SERVICE_CODE
     */
    public Number getProductServiceCode() {
        return (Number) getAttributeInternal(PRODUCTSERVICECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_SERVICE_CODE using the alias name ProductServiceCode.
     * @param value value to set the PRODUCT_SERVICE_CODE
     */
    public void setProductServiceCode(Number value) {
        setAttributeInternal(PRODUCTSERVICECODE, value);
    }

    /**
     * Gets the attribute value for PROJECT_POP_END_DATE using the alias name ProjectPopEndDate.
     * @return the PROJECT_POP_END_DATE
     */
    public Date getProjectPopEndDate() {
        return (Date) getAttributeInternal(PROJECTPOPENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_POP_END_DATE using the alias name ProjectPopEndDate.
     * @param value value to set the PROJECT_POP_END_DATE
     */
    public void setProjectPopEndDate(Date value) {
        setAttributeInternal(PROJECTPOPENDDATE, value);
    }

    /**
     * Gets the attribute value for PROJECT_POP_START_DATE using the alias name ProjectPopStartDate.
     * @return the PROJECT_POP_START_DATE
     */
    public Date getProjectPopStartDate() {
        return (Date) getAttributeInternal(PROJECTPOPSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_POP_START_DATE using the alias name ProjectPopStartDate.
     * @param value value to set the PROJECT_POP_START_DATE
     */
    public void setProjectPopStartDate(Date value) {
        setAttributeInternal(PROJECTPOPSTARTDATE, value);
    }

    /**
     * Gets the attribute value for PURPOSE using the alias name Purpose.
     * @return the PURPOSE
     */
    public String getPurpose() {
        return (String) getAttributeInternal(PURPOSE);
    }

    /**
     * Sets <code>value</code> as attribute value for PURPOSE using the alias name Purpose.
     * @param value value to set the PURPOSE
     */
    public void setPurpose(String value) {
        setAttributeInternal(PURPOSE, value);
    }

    /**
     * Gets the attribute value for RECURRING_ITEM using the alias name RecurringItem.
     * @return the RECURRING_ITEM
     */
    public String getRecurringItem() {
        return (String) getAttributeInternal(RECURRINGITEM);
    }

    /**
     * Sets <code>value</code> as attribute value for RECURRING_ITEM using the alias name RecurringItem.
     * @param value value to set the RECURRING_ITEM
     */
    public void setRecurringItem(String value) {
        setAttributeInternal(RECURRINGITEM, value);
    }

    /**
     * Gets the attribute value for REIMBURSABLE_AGENCY using the alias name ReimbursableAgency.
     * @return the REIMBURSABLE_AGENCY
     */
    public String getReimbursableAgency() {
        return (String) getAttributeInternal(REIMBURSABLEAGENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURSABLE_AGENCY using the alias name ReimbursableAgency.
     * @param value value to set the REIMBURSABLE_AGENCY
     */
    public void setReimbursableAgency(String value) {
        setAttributeInternal(REIMBURSABLEAGENCY, value);
    }

    /**
     * Gets the attribute value for REIMBURSABLE_AMT using the alias name ReimbursableAmt.
     * @return the REIMBURSABLE_AMT
     */
    public String getReimbursableAmt() {
        return (String) getAttributeInternal(REIMBURSABLEAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURSABLE_AMT using the alias name ReimbursableAmt.
     * @param value value to set the REIMBURSABLE_AMT
     */
    public void setReimbursableAmt(String value) {
        setAttributeInternal(REIMBURSABLEAMT, value);
    }

    /**
     * Gets the attribute value for RELEASE_NUMBER using the alias name ReleaseNumber.
     * @return the RELEASE_NUMBER
     */
    public String getReleaseNumber() {
        return (String) getAttributeInternal(RELEASENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for RELEASE_NUMBER using the alias name ReleaseNumber.
     * @param value value to set the RELEASE_NUMBER
     */
    public void setReleaseNumber(String value) {
        setAttributeInternal(RELEASENUMBER, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for REQUIRED_AWARD_DATE using the alias name RequiredAwardDate.
     * @return the REQUIRED_AWARD_DATE
     */
    public Date getRequiredAwardDate() {
        return (Date) getAttributeInternal(REQUIREDAWARDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUIRED_AWARD_DATE using the alias name RequiredAwardDate.
     * @param value value to set the REQUIRED_AWARD_DATE
     */
    public void setRequiredAwardDate(Date value) {
        setAttributeInternal(REQUIREDAWARDDATE, value);
    }

    /**
     * Gets the attribute value for REQUIREMENT_TYPE using the alias name RequirementType.
     * @return the REQUIREMENT_TYPE
     */
    public Number getRequirementType() {
        return (Number) getAttributeInternal(REQUIREMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUIREMENT_TYPE using the alias name RequirementType.
     * @param value value to set the REQUIREMENT_TYPE
     */
    public void setRequirementType(Number value) {
        setAttributeInternal(REQUIREMENTTYPE, value);
    }

    /**
     * Gets the attribute value for REQUISITION_NO using the alias name RequisitionNo.
     * @return the REQUISITION_NO
     */
    public String getRequisitionNo() {
        return (String) getAttributeInternal(REQUISITIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUISITION_NO using the alias name RequisitionNo.
     * @param value value to set the REQUISITION_NO
     */
    public void setRequisitionNo(String value) {
        setAttributeInternal(REQUISITIONNO, value);
    }

    /**
     * Gets the attribute value for SERVICE_OR_REIMBURSABLE using the alias name ServiceOrReimbursable.
     * @return the SERVICE_OR_REIMBURSABLE
     */
    public Number getServiceOrReimbursable() {
        return (Number) getAttributeInternal(SERVICEORREIMBURSABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for SERVICE_OR_REIMBURSABLE using the alias name ServiceOrReimbursable.
     * @param value value to set the SERVICE_OR_REIMBURSABLE
     */
    public void setServiceOrReimbursable(Number value) {
        setAttributeInternal(SERVICEORREIMBURSABLE, value);
    }

    /**
     * Gets the attribute value for SUBMIT_FLAG using the alias name SubmitFlag.
     * @return the SUBMIT_FLAG
     */
    public String getSubmitFlag() {
        return (String) getAttributeInternal(SUBMITFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMIT_FLAG using the alias name SubmitFlag.
     * @param value value to set the SUBMIT_FLAG
     */
    public void setSubmitFlag(String value) {
        setAttributeInternal(SUBMITFLAG, value);
    }

    /**
     * Gets the attribute value for TOTAL_DLARS_FOR_CURT_FY using the alias name TotalDlarsForCurtFy.
     * @return the TOTAL_DLARS_FOR_CURT_FY
     */
    public Number getTotalDlarsForCurtFy() {
        return (Number) getAttributeInternal(TOTALDLARSFORCURTFY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_DLARS_FOR_CURT_FY using the alias name TotalDlarsForCurtFy.
     * @param value value to set the TOTAL_DLARS_FOR_CURT_FY
     */
    public void setTotalDlarsForCurtFy(Number value) {
        setAttributeInternal(TOTALDLARSFORCURTFY, value);
    }

    /**
     * Gets the attribute value for ZERO_DOLLAR_REQN using the alias name ZeroDollarReqn.
     * @return the ZERO_DOLLAR_REQN
     */
    public String getZeroDollarReqn() {
        return (String) getAttributeInternal(ZERODOLLARREQN);
    }

    /**
     * Sets <code>value</code> as attribute value for ZERO_DOLLAR_REQN using the alias name ZeroDollarReqn.
     * @param value value to set the ZERO_DOLLAR_REQN
     */
    public void setZeroDollarReqn(String value) {
        setAttributeInternal(ZERODOLLARREQN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalAmountRemaining.
     * @return the TotalAmountRemaining
     */
    public Number getTotalAmountRemaining() {
        return (Number) getAttributeInternal(TOTALAMOUNTREMAINING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalAmountRemaining.
     * @param value value to set the  TotalAmountRemaining
     */
    public void setTotalAmountRemaining(Number value) {
        setAttributeInternal(TOTALAMOUNTREMAINING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransProjectValueCode.
     * @return the TransProjectValueCode
     */
    public String getTransProjectValueCode() {
        return (String) getAttributeInternal(TRANSPROJECTVALUECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransProjectValueCode.
     * @param value value to set the  TransProjectValueCode
     */
    public void setTransProjectValueCode(String value) {
        setAttributeInternal(TRANSPROJECTVALUECODE, value);
    }

    /**
     * Gets the attribute value for BRANCH using the alias name Branch.
     * @return the BRANCH
     */
    public String getBranch() {
        return (String) getAttributeInternal(BRANCH);
    }

    /**
     * Sets <code>value</code> as attribute value for BRANCH using the alias name Branch.
     * @param value value to set the BRANCH
     */
    public void setBranch(String value) {
        setAttributeInternal(BRANCH, value);
    }

    /**
     * Gets the attribute value for DIVISION using the alias name Division.
     * @return the DIVISION
     */
    public String getDivision() {
        return (String) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION using the alias name Division.
     * @param value value to set the DIVISION
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for DUE_DATE using the alias name DueDate.
     * @return the DUE_DATE
     */
    public Date getDueDate() {
        return (Date) getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DUE_DATE using the alias name DueDate.
     * @param value value to set the DUE_DATE
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSLANumdays.
     * @return the TransSLANumdays
     */
    public String getTransSLANumdays() {
        return (String) getAttributeInternal(TRANSSLANUMDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSLANumdays.
     * @param value value to set the  TransSLANumdays
     */
    public void setTransSLANumdays(String value) {
        setAttributeInternal(TRANSSLANUMDAYS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransReqType.
     * @return the TransReqType
     */
    public String getTransReqType() {
        return (String) getAttributeInternal(TRANSREQTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransReqType.
     * @param value value to set the  TransReqType
     */
    public void setTransReqType(String value) {
        setAttributeInternal(TRANSREQTYPE, value);
    }

    /**
     * Gets the attribute value for SUB_OFC using the alias name SubOfc.
     * @return the SUB_OFC
     */
    public Number getSubOfc() {
        return (Number) getAttributeInternal(SUBOFC);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_OFC using the alias name SubOfc.
     * @param value value to set the SUB_OFC
     */
    public void setSubOfc(Number value) {
        setAttributeInternal(SUBOFC, value);
    }

    /**
     * Gets the attribute value for SUPER_OFC using the alias name SuperOfc.
     * @return the SUPER_OFC
     */
    public Number getSuperOfc() {
        return (Number) getAttributeInternal(SUPEROFC);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPER_OFC using the alias name SuperOfc.
     * @param value value to set the SUPER_OFC
     */
    public void setSuperOfc(Number value) {
        setAttributeInternal(SUPEROFC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSupOfcCode.
     * @return the TransSupOfcCode
     */
    public String getTransSupOfcCode() {
        return (String) getAttributeInternal(TRANSSUPOFCCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSupOfcCode.
     * @param value value to set the  TransSupOfcCode
     */
    public void setTransSupOfcCode(String value) {
        setAttributeInternal(TRANSSUPOFCCODE, value);
    }

    /**
     * Gets the attribute value for TOTAL_DLARS_CRNT_YR using the alias name TotalDlarsCrntYr.
     * @return the TOTAL_DLARS_CRNT_YR
     */
    public Number getTotalDlarsCrntYr() {
        return (Number) getAttributeInternal(TOTALDLARSCRNTYR);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_DLARS_CRNT_YR using the alias name TotalDlarsCrntYr.
     * @param value value to set the TOTAL_DLARS_CRNT_YR
     */
    public void setTotalDlarsCrntYr(Number value) {
        setAttributeInternal(TOTALDLARSCRNTYR, value);
    }

    /**
     * Gets the attribute value for REQUEST_TITLE using the alias name RequestTitle.
     * @return the REQUEST_TITLE
     */
    public String getRequestTitle() {
        return (String) getAttributeInternal(REQUESTTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_TITLE using the alias name RequestTitle.
     * @param value value to set the REQUEST_TITLE
     */
    public void setRequestTitle(String value) {
        setAttributeInternal(REQUESTTITLE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PointOfContactView.
     */
    public RowIterator getPointOfContactView() {
        return (RowIterator)getAttributeInternal(POINTOFCONTACTVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AapNotificationView.
     */
    public RowIterator getAapNotificationView() {
        return (RowIterator)getAttributeInternal(AAPNOTIFICATIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DetailedExpensesView.
     */
    public RowIterator getDetailedExpensesView() {
        return (RowIterator)getAttributeInternal(DETAILEDEXPENSESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AapCollaborationView.
     */
    public RowIterator getAapCollaborationView() {
        return (RowIterator)getAttributeInternal(AAPCOLLABORATIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AapCommentsVO.
     */
    public RowIterator getAapCommentsVO() {
        return (RowIterator)getAttributeInternal(AAPCOMMENTSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NAICSReferenceView.
     */
    public RowSet getNAICSReferenceView() {
        return (RowSet)getAttributeInternal(NAICSREFERENCEVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LeadManagingCenterLOV.
     */
    public RowSet getLeadManagingCenterLOV() {
        return (RowSet)getAttributeInternal(LEADMANAGINGCENTERLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProrityLevelLOV.
     */
    public RowSet getProrityLevelLOV() {
        return (RowSet)getAttributeInternal(PRORITYLEVELLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ServiceOrReimbursableLOV.
     */
    public RowSet getServiceOrReimbursableLOV() {
        return (RowSet)getAttributeInternal(SERVICEORREIMBURSABLELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SORList.
     */
    public RowSet getSORList() {
        return (RowSet)getAttributeInternal(SORLIST);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CollaborationItemLOV.
     */
    public RowSet getCollaborationItemLOV() {
        return (RowSet)getAttributeInternal(COLLABORATIONITEMLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AcqisitionStatusLOV.
     */
    public RowSet getAcqisitionStatusLOV() {
        return (RowSet)getAttributeInternal(ACQISITIONSTATUSLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OptionYearLOV.
     */
    public RowSet getOptionYearLOV() {
        return (RowSet)getAttributeInternal(OPTIONYEARLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AnticipatedActionTypeLOV.
     */
    public RowSet getAnticipatedActionTypeLOV() {
        return (RowSet)getAttributeInternal(ANTICIPATEDACTIONTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PotentialContractTypeLOV.
     */
    public RowSet getPotentialContractTypeLOV() {
        return (RowSet)getAttributeInternal(POTENTIALCONTRACTTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RequirementTypeLOV.
     */
    public RowSet getRequirementTypeLOV() {
        return (RowSet)getAttributeInternal(REQUIREMENTTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CommodityTypeLOV.
     */
    public RowSet getCommodityTypeLOV() {
        return (RowSet)getAttributeInternal(COMMODITYTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductServiceCodeLOV.
     */
    public RowSet getProductServiceCodeLOV() {
        return (RowSet)getAttributeInternal(PRODUCTSERVICECODELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CompetitionTypeLOV.
     */
    public RowSet getCompetitionTypeLOV() {
        return (RowSet)getAttributeInternal(COMPETITIONTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EstimatedTotalProjectValueLOV.
     */
    public RowSet getEstimatedTotalProjectValueLOV() {
        return (RowSet)getAttributeInternal(ESTIMATEDTOTALPROJECTVALUELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GrantsCommodityLOV.
     */
    public RowSet getGrantsCommodityLOV() {
        return (RowSet)getAttributeInternal(GRANTSCOMMODITYLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesNoView.
     */
    public RowSet getYesNoView() {
        return (RowSet)getAttributeInternal(YESNOVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FiscalYearLOV.
     */
    public RowSet getFiscalYearLOV() {
        return (RowSet)getAttributeInternal(FISCALYEARLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DetailedExpensesVO.
     */
    public RowSet getDetailedExpensesVO() {
        return (RowSet)getAttributeInternal(DETAILEDEXPENSESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SubOfficeLOV.
     */
    public RowSet getSubOfficeLOV() {
        return (RowSet)getAttributeInternal(SUBOFFICELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupOfficeLOV.
     */
    public RowSet getSupOfficeLOV() {
        return (RowSet)getAttributeInternal(SUPOFFICELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CurrentYearProjectValueLOV.
     */
    public RowSet getCurrentYearProjectValueLOV() {
        return (RowSet)getAttributeInternal(CURRENTYEARPROJECTVALUELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EstimatedValueRangeVO.
     */
    public RowSet getEstimatedValueRangeVO() {
        return (RowSet)getAttributeInternal(ESTIMATEDVALUERANGEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EstimatedProjectValueRangeLOV.
     */
    public RowSet getEstimatedProjectValueRangeLOV() {
        return (RowSet)getAttributeInternal(ESTIMATEDPROJECTVALUERANGELOV);
    }


}
